// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"database/sql"
	"github.com/go-chi/chi/v5"
	"github.com/kthulu/kthulu-go/backend/core"
	"github.com/kthulu/kthulu-go/backend/core/metrics"
	"github.com/kthulu/kthulu-go/backend/internal/modules"
	"github.com/kthulu/kthulu-go/backend/internal/modules/flags"
	"github.com/kthulu/kthulu-go/backend/internal/observability"
	"go.uber.org/fx"
	"net/http"
)

// Injectors from wire.go:

// InitializeApp sets up application dependencies using Wire.
func InitializeApp() appSet {
	v := _wireValue
	v2 := _wireValue2
	v3 := _wireValue3
	v4 := _wireValue4
	mainAppSet := appSet{
		RouterProvider:      v,
		HTTPServerProvider:  v2,
		ValidateStartupFunc: v3,
		RegisterHooksFunc:   v4,
	}
	return mainAppSet
}

var (
	_wireValue  = routerProviderValue
	_wireValue2 = httpServerProviderValue
	_wireValue3 = validateStartupFuncValue
	_wireValue4 = registerHooksFuncValue
)

// wire.go:

type routerProviderType = func(p struct {
	fx.In

	RouteRegistry *modules.RouteRegistry
	DB            *sql.DB
	Logger        observability.Logger
	Config        *core.Config
	TokenManager  core.TokenManager
	Flags         flags.HeaderConfig
	Metrics       *metrics.PrometheusMetrics
}) chi.Router

type httpServerProviderType = func(r chi.Router, cfg *core.Config, logger observability.Logger) *http.Server

type validateStartupFuncType = func(db *sql.DB, cfg *core.Config, logger observability.Logger) error

type registerHooksFuncType = func(lc fx.Lifecycle, srv *http.Server, db *sql.DB, logger observability.Logger)

var (
	routerProviderValue      routerProviderType      = newRouter
	httpServerProviderValue  httpServerProviderType  = newHTTPServer
	validateStartupFuncValue validateStartupFuncType = validateStartup
	registerHooksFuncValue   registerHooksFuncType   = registerHooks
)

type appSet struct {
	RouterProvider      routerProviderType
	HTTPServerProvider  httpServerProviderType
	ValidateStartupFunc validateStartupFuncType
	RegisterHooksFunc   registerHooksFuncType
}
