# golangci-lint configuration for Kthulu project
# Compatible with Go 1.23.x

run:
  timeout: 5m
  go: "1.23"
  modules-download-mode: readonly
  allow-parallel-runners: true

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

issues:
  exclude-dirs:
    - vendor
    - node_modules
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_generated\\.go$"
    - ".*\\.gen\\.go$"
  uniq-by-line: true

linters-settings:
  # Cyclomatic complexity
  gocyclo:
    min-complexity: 15

  # Cognitive complexity
  gocognit:
    min-complexity: 20

  # Function length
  funlen:
    lines: 100
    statements: 50

  # Line length
  lll:
    line-length: 120

  # Govet settings
  govet:
    enable-all: true
    disable:
      - fieldalignment # Can be noisy for structs

  # Gosec security settings
  gosec:
    severity: medium
    confidence: medium
    excludes:
      - G104 # Audit errors not checked (too noisy)
      - G204 # Subprocess launched with variable (common in CLI)

  # Ineffassign settings
  ineffassign:
    check-exported: true

  # Misspell settings
  misspell:
    locale: US
    ignore-words:
      - kthulu
      - oauth
      - verifactu

  # Unused settings
  unused:
    check-exported: false

  # Errcheck settings
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*database/sql.Rows).Close
      - (*database/sql.DB).Close

  # Revive settings (replacement for golint)
  revive:
    min-confidence: 0.8
    rules:
      - name: var-naming
        severity: warning
        disabled: false
        arguments:
          - ["ID"] # Allow ID instead of Id
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: true # Too strict for internal packages

  # Goimports settings
  goimports:
    local-prefixes: backend

  # Gocritic settings
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
    disabled-checks:
      - commentedOutCode
      - whyNoLint

  # Staticcheck settings
  staticcheck:
    checks: ["all"]

linters:
  disable-all: true
  enable:
    # Error detection
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # Style
    - gofmt
    - goimports
    - revive
    - misspell

    # Complexity
    - gocyclo
    - gocognit
    - funlen

    # Security
    - gosec

    # Performance
    - prealloc

    # Bugs
    - gocritic
    - unconvert
    - unparam

    # Additional useful linters
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errorlint
    - copyloopvar  # Replacement for deprecated exportloopref
    - goconst
    - goheader
    - goprintffuncname
    - makezero
    - nilerr
    - nolintlint
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - tparallel
    - wastedassign
    - whitespace

  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
  fix: false

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen

    # Exclude some linters from running on CLI files
    - path: cmd/
      linters:
        - gocyclo
        - funlen

    # Exclude some linters from running on generated files
    - path: ".*\\.gen\\.go"
      linters:
        - all

    # Exclude some linters from running on migration files
    - path: migrations/
      linters:
        - all

    # Exclude some linters from running on examples
    - path: examples/
      linters:
        - errcheck
        - gosec

    # Allow long lines in comments
    - source: "^//.*"
      linters:
        - lll

    # Allow long lines in struct tags
    - source: "`.*`$"
      linters:
        - lll

  exclude:
    # Exclude common false positives
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*print(f|ln)?|os\\.(Un)?Setenv). is not checked"
    - "exported (type|method|function) .* should have comment or be unexported"
    - "ST1000: at least one file in a package should have a package comment"

severity:
  default-severity: error
  case-sensitive: false
  rules:
    - linters:
        - revive
      severity: warning
    - linters:
        - misspell
      severity: info