// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/calendar_repository.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/pmaojo/kthulu-go/backend/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockCalendarRepository is a mock of CalendarRepository interface.
type MockCalendarRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCalendarRepositoryMockRecorder
}

// MockCalendarRepositoryMockRecorder is the mock recorder for MockCalendarRepository.
type MockCalendarRepositoryMockRecorder struct {
	mock *MockCalendarRepository
}

// NewMockCalendarRepository creates a new mock instance.
func NewMockCalendarRepository(ctrl *gomock.Controller) *MockCalendarRepository {
	mock := &MockCalendarRepository{ctrl: ctrl}
	mock.recorder = &MockCalendarRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCalendarRepository) EXPECT() *MockCalendarRepositoryMockRecorder {
	return m.recorder
}

// CreateAttendee mocks base method.
func (m *MockCalendarRepository) CreateAttendee(ctx context.Context, attendee *domain.Attendee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttendee", ctx, attendee)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAttendee indicates an expected call of CreateAttendee.
func (mr *MockCalendarRepositoryMockRecorder) CreateAttendee(ctx, attendee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttendee", reflect.TypeOf((*MockCalendarRepository)(nil).CreateAttendee), ctx, attendee)
}

// CreateAvailabilitySlot mocks base method.
func (m *MockCalendarRepository) CreateAvailabilitySlot(ctx context.Context, slot *domain.AvailabilitySlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAvailabilitySlot", ctx, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAvailabilitySlot indicates an expected call of CreateAvailabilitySlot.
func (mr *MockCalendarRepositoryMockRecorder) CreateAvailabilitySlot(ctx, slot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAvailabilitySlot", reflect.TypeOf((*MockCalendarRepository)(nil).CreateAvailabilitySlot), ctx, slot)
}

// CreateBooking mocks base method.
func (m *MockCalendarRepository) CreateBooking(ctx context.Context, booking *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockCalendarRepositoryMockRecorder) CreateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockCalendarRepository)(nil).CreateBooking), ctx, booking)
}

// CreateCalendar mocks base method.
func (m *MockCalendarRepository) CreateCalendar(ctx context.Context, calendar *domain.Calendar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCalendar", ctx, calendar)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCalendar indicates an expected call of CreateCalendar.
func (mr *MockCalendarRepositoryMockRecorder) CreateCalendar(ctx, calendar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCalendar", reflect.TypeOf((*MockCalendarRepository)(nil).CreateCalendar), ctx, calendar)
}

// CreateEvent mocks base method.
func (m *MockCalendarRepository) CreateEvent(ctx context.Context, event *domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateEvent indicates an expected call of CreateEvent.
func (mr *MockCalendarRepositoryMockRecorder) CreateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEvent", reflect.TypeOf((*MockCalendarRepository)(nil).CreateEvent), ctx, event)
}

// CreateReminder mocks base method.
func (m *MockCalendarRepository) CreateReminder(ctx context.Context, reminder *domain.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReminder", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateReminder indicates an expected call of CreateReminder.
func (mr *MockCalendarRepositoryMockRecorder) CreateReminder(ctx, reminder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReminder", reflect.TypeOf((*MockCalendarRepository)(nil).CreateReminder), ctx, reminder)
}

// DeleteAttendee mocks base method.
func (m *MockCalendarRepository) DeleteAttendee(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAttendee", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAttendee indicates an expected call of DeleteAttendee.
func (mr *MockCalendarRepositoryMockRecorder) DeleteAttendee(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAttendee", reflect.TypeOf((*MockCalendarRepository)(nil).DeleteAttendee), ctx, id)
}

// DeleteAvailabilitySlot mocks base method.
func (m *MockCalendarRepository) DeleteAvailabilitySlot(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvailabilitySlot", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvailabilitySlot indicates an expected call of DeleteAvailabilitySlot.
func (mr *MockCalendarRepositoryMockRecorder) DeleteAvailabilitySlot(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvailabilitySlot", reflect.TypeOf((*MockCalendarRepository)(nil).DeleteAvailabilitySlot), ctx, id)
}

// DeleteBooking mocks base method.
func (m *MockCalendarRepository) DeleteBooking(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBooking", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBooking indicates an expected call of DeleteBooking.
func (mr *MockCalendarRepositoryMockRecorder) DeleteBooking(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBooking", reflect.TypeOf((*MockCalendarRepository)(nil).DeleteBooking), ctx, id)
}

// DeleteCalendar mocks base method.
func (m *MockCalendarRepository) DeleteCalendar(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCalendar", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCalendar indicates an expected call of DeleteCalendar.
func (mr *MockCalendarRepositoryMockRecorder) DeleteCalendar(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCalendar", reflect.TypeOf((*MockCalendarRepository)(nil).DeleteCalendar), ctx, id)
}

// DeleteEvent mocks base method.
func (m *MockCalendarRepository) DeleteEvent(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteEvent", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteEvent indicates an expected call of DeleteEvent.
func (mr *MockCalendarRepositoryMockRecorder) DeleteEvent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteEvent", reflect.TypeOf((*MockCalendarRepository)(nil).DeleteEvent), ctx, id)
}

// DeleteReminder mocks base method.
func (m *MockCalendarRepository) DeleteReminder(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteReminder", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteReminder indicates an expected call of DeleteReminder.
func (mr *MockCalendarRepositoryMockRecorder) DeleteReminder(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteReminder", reflect.TypeOf((*MockCalendarRepository)(nil).DeleteReminder), ctx, id)
}

// GetAttendees mocks base method.
func (m *MockCalendarRepository) GetAttendees(ctx context.Context, eventID uint) ([]domain.Attendee, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttendees", ctx, eventID)
	ret0, _ := ret[0].([]domain.Attendee)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttendees indicates an expected call of GetAttendees.
func (mr *MockCalendarRepositoryMockRecorder) GetAttendees(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttendees", reflect.TypeOf((*MockCalendarRepository)(nil).GetAttendees), ctx, eventID)
}

// GetAvailabilitySlot mocks base method.
func (m *MockCalendarRepository) GetAvailabilitySlot(ctx context.Context, id uint) (*domain.AvailabilitySlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailabilitySlot", ctx, id)
	ret0, _ := ret[0].(*domain.AvailabilitySlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailabilitySlot indicates an expected call of GetAvailabilitySlot.
func (mr *MockCalendarRepositoryMockRecorder) GetAvailabilitySlot(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailabilitySlot", reflect.TypeOf((*MockCalendarRepository)(nil).GetAvailabilitySlot), ctx, id)
}

// GetBooking mocks base method.
func (m *MockCalendarRepository) GetBooking(ctx context.Context, id uint) (*domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooking", ctx, id)
	ret0, _ := ret[0].(*domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooking indicates an expected call of GetBooking.
func (mr *MockCalendarRepositoryMockRecorder) GetBooking(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooking", reflect.TypeOf((*MockCalendarRepository)(nil).GetBooking), ctx, id)
}

// GetBookingsByTimeRange mocks base method.
func (m *MockCalendarRepository) GetBookingsByTimeRange(ctx context.Context, calendarID uint, start, end time.Time) ([]domain.Booking, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsByTimeRange", ctx, calendarID, start, end)
	ret0, _ := ret[0].([]domain.Booking)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsByTimeRange indicates an expected call of GetBookingsByTimeRange.
func (mr *MockCalendarRepositoryMockRecorder) GetBookingsByTimeRange(ctx, calendarID, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsByTimeRange", reflect.TypeOf((*MockCalendarRepository)(nil).GetBookingsByTimeRange), ctx, calendarID, start, end)
}

// GetCalendar mocks base method.
func (m *MockCalendarRepository) GetCalendar(ctx context.Context, id uint) (*domain.Calendar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCalendar", ctx, id)
	ret0, _ := ret[0].(*domain.Calendar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCalendar indicates an expected call of GetCalendar.
func (mr *MockCalendarRepositoryMockRecorder) GetCalendar(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCalendar", reflect.TypeOf((*MockCalendarRepository)(nil).GetCalendar), ctx, id)
}

// GetEvent mocks base method.
func (m *MockCalendarRepository) GetEvent(ctx context.Context, id uint) (*domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEvent", ctx, id)
	ret0, _ := ret[0].(*domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEvent indicates an expected call of GetEvent.
func (mr *MockCalendarRepositoryMockRecorder) GetEvent(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEvent", reflect.TypeOf((*MockCalendarRepository)(nil).GetEvent), ctx, id)
}

// GetEventsByStatus mocks base method.
func (m *MockCalendarRepository) GetEventsByStatus(ctx context.Context, calendarID uint, status domain.EventStatus) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByStatus", ctx, calendarID, status)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByStatus indicates an expected call of GetEventsByStatus.
func (mr *MockCalendarRepositoryMockRecorder) GetEventsByStatus(ctx, calendarID, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByStatus", reflect.TypeOf((*MockCalendarRepository)(nil).GetEventsByStatus), ctx, calendarID, status)
}

// GetEventsByTimeRange mocks base method.
func (m *MockCalendarRepository) GetEventsByTimeRange(ctx context.Context, calendarID uint, start, end time.Time) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByTimeRange", ctx, calendarID, start, end)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByTimeRange indicates an expected call of GetEventsByTimeRange.
func (mr *MockCalendarRepositoryMockRecorder) GetEventsByTimeRange(ctx, calendarID, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByTimeRange", reflect.TypeOf((*MockCalendarRepository)(nil).GetEventsByTimeRange), ctx, calendarID, start, end)
}

// GetEventsByType mocks base method.
func (m *MockCalendarRepository) GetEventsByType(ctx context.Context, calendarID uint, eventType domain.EventType) ([]domain.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEventsByType", ctx, calendarID, eventType)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEventsByType indicates an expected call of GetEventsByType.
func (mr *MockCalendarRepositoryMockRecorder) GetEventsByType(ctx, calendarID, eventType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEventsByType", reflect.TypeOf((*MockCalendarRepository)(nil).GetEventsByType), ctx, calendarID, eventType)
}

// GetPendingReminders mocks base method.
func (m *MockCalendarRepository) GetPendingReminders(ctx context.Context, before time.Time) ([]domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingReminders", ctx, before)
	ret0, _ := ret[0].([]domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingReminders indicates an expected call of GetPendingReminders.
func (mr *MockCalendarRepositoryMockRecorder) GetPendingReminders(ctx, before interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingReminders", reflect.TypeOf((*MockCalendarRepository)(nil).GetPendingReminders), ctx, before)
}

// GetReminders mocks base method.
func (m *MockCalendarRepository) GetReminders(ctx context.Context, eventID uint) ([]domain.Reminder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReminders", ctx, eventID)
	ret0, _ := ret[0].([]domain.Reminder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReminders indicates an expected call of GetReminders.
func (mr *MockCalendarRepositoryMockRecorder) GetReminders(ctx, eventID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReminders", reflect.TypeOf((*MockCalendarRepository)(nil).GetReminders), ctx, eventID)
}

// ListAvailabilitySlots mocks base method.
func (m *MockCalendarRepository) ListAvailabilitySlots(ctx context.Context, calendarID uint, start, end time.Time) ([]domain.AvailabilitySlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAvailabilitySlots", ctx, calendarID, start, end)
	ret0, _ := ret[0].([]domain.AvailabilitySlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAvailabilitySlots indicates an expected call of ListAvailabilitySlots.
func (mr *MockCalendarRepositoryMockRecorder) ListAvailabilitySlots(ctx, calendarID, start, end interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAvailabilitySlots", reflect.TypeOf((*MockCalendarRepository)(nil).ListAvailabilitySlots), ctx, calendarID, start, end)
}

// ListBookings mocks base method.
func (m *MockCalendarRepository) ListBookings(ctx context.Context, calendarID uint, page, pageSize int) ([]domain.Booking, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBookings", ctx, calendarID, page, pageSize)
	ret0, _ := ret[0].([]domain.Booking)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListBookings indicates an expected call of ListBookings.
func (mr *MockCalendarRepositoryMockRecorder) ListBookings(ctx, calendarID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBookings", reflect.TypeOf((*MockCalendarRepository)(nil).ListBookings), ctx, calendarID, page, pageSize)
}

// ListCalendars mocks base method.
func (m *MockCalendarRepository) ListCalendars(ctx context.Context, ownerID uint, page, pageSize int) ([]domain.Calendar, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCalendars", ctx, ownerID, page, pageSize)
	ret0, _ := ret[0].([]domain.Calendar)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListCalendars indicates an expected call of ListCalendars.
func (mr *MockCalendarRepositoryMockRecorder) ListCalendars(ctx, ownerID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCalendars", reflect.TypeOf((*MockCalendarRepository)(nil).ListCalendars), ctx, ownerID, page, pageSize)
}

// ListEvents mocks base method.
func (m *MockCalendarRepository) ListEvents(ctx context.Context, calendarID uint, page, pageSize int) ([]domain.Event, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEvents", ctx, calendarID, page, pageSize)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListEvents indicates an expected call of ListEvents.
func (mr *MockCalendarRepositoryMockRecorder) ListEvents(ctx, calendarID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEvents", reflect.TypeOf((*MockCalendarRepository)(nil).ListEvents), ctx, calendarID, page, pageSize)
}

// SearchEvents mocks base method.
func (m *MockCalendarRepository) SearchEvents(ctx context.Context, calendarID uint, query string, page, pageSize int) ([]domain.Event, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchEvents", ctx, calendarID, query, page, pageSize)
	ret0, _ := ret[0].([]domain.Event)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchEvents indicates an expected call of SearchEvents.
func (mr *MockCalendarRepositoryMockRecorder) SearchEvents(ctx, calendarID, query, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchEvents", reflect.TypeOf((*MockCalendarRepository)(nil).SearchEvents), ctx, calendarID, query, page, pageSize)
}

// UpdateAttendee mocks base method.
func (m *MockCalendarRepository) UpdateAttendee(ctx context.Context, attendee *domain.Attendee) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttendee", ctx, attendee)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttendee indicates an expected call of UpdateAttendee.
func (mr *MockCalendarRepositoryMockRecorder) UpdateAttendee(ctx, attendee interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttendee", reflect.TypeOf((*MockCalendarRepository)(nil).UpdateAttendee), ctx, attendee)
}

// UpdateAvailabilitySlot mocks base method.
func (m *MockCalendarRepository) UpdateAvailabilitySlot(ctx context.Context, slot *domain.AvailabilitySlot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvailabilitySlot", ctx, slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvailabilitySlot indicates an expected call of UpdateAvailabilitySlot.
func (mr *MockCalendarRepositoryMockRecorder) UpdateAvailabilitySlot(ctx, slot interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvailabilitySlot", reflect.TypeOf((*MockCalendarRepository)(nil).UpdateAvailabilitySlot), ctx, slot)
}

// UpdateBooking mocks base method.
func (m *MockCalendarRepository) UpdateBooking(ctx context.Context, booking *domain.Booking) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBooking", ctx, booking)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateBooking indicates an expected call of UpdateBooking.
func (mr *MockCalendarRepositoryMockRecorder) UpdateBooking(ctx, booking interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBooking", reflect.TypeOf((*MockCalendarRepository)(nil).UpdateBooking), ctx, booking)
}

// UpdateCalendar mocks base method.
func (m *MockCalendarRepository) UpdateCalendar(ctx context.Context, calendar *domain.Calendar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCalendar", ctx, calendar)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCalendar indicates an expected call of UpdateCalendar.
func (mr *MockCalendarRepositoryMockRecorder) UpdateCalendar(ctx, calendar interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCalendar", reflect.TypeOf((*MockCalendarRepository)(nil).UpdateCalendar), ctx, calendar)
}

// UpdateEvent mocks base method.
func (m *MockCalendarRepository) UpdateEvent(ctx context.Context, event *domain.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateEvent", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateEvent indicates an expected call of UpdateEvent.
func (mr *MockCalendarRepositoryMockRecorder) UpdateEvent(ctx, event interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateEvent", reflect.TypeOf((*MockCalendarRepository)(nil).UpdateEvent), ctx, event)
}

// UpdateReminder mocks base method.
func (m *MockCalendarRepository) UpdateReminder(ctx context.Context, reminder *domain.Reminder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateReminder", ctx, reminder)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateReminder indicates an expected call of UpdateReminder.
func (mr *MockCalendarRepositoryMockRecorder) UpdateReminder(ctx, reminder interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateReminder", reflect.TypeOf((*MockCalendarRepository)(nil).UpdateReminder), ctx, reminder)
}
