// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/inventory_repository.go

// Package usecase is a generated GoMock package.
package usecase

import (
	context "context"
	reflect "reflect"

	domain "github.com/pmaojo/kthulu-go/backend/internal/domain"

	gomock "github.com/golang/mock/gomock"
)

// MockInventoryRepository is a mock of InventoryRepository interface.
type MockInventoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockInventoryRepositoryMockRecorder
}

// MockInventoryRepositoryMockRecorder is the mock recorder for MockInventoryRepository.
type MockInventoryRepositoryMockRecorder struct {
	mock *MockInventoryRepository
}

// NewMockInventoryRepository creates a new mock instance.
func NewMockInventoryRepository(ctrl *gomock.Controller) *MockInventoryRepository {
	mock := &MockInventoryRepository{ctrl: ctrl}
	mock.recorder = &MockInventoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInventoryRepository) EXPECT() *MockInventoryRepositoryMockRecorder {
	return m.recorder
}

// CreateInventoryItem mocks base method.
func (m *MockInventoryRepository) CreateInventoryItem(ctx context.Context, item *domain.InventoryItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventoryItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateInventoryItem indicates an expected call of CreateInventoryItem.
func (mr *MockInventoryRepositoryMockRecorder) CreateInventoryItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventoryItem", reflect.TypeOf((*MockInventoryRepository)(nil).CreateInventoryItem), ctx, item)
}

// CreateStockAdjustment mocks base method.
func (m *MockInventoryRepository) CreateStockAdjustment(ctx context.Context, adjustment *domain.StockAdjustment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStockAdjustment", ctx, adjustment)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStockAdjustment indicates an expected call of CreateStockAdjustment.
func (mr *MockInventoryRepositoryMockRecorder) CreateStockAdjustment(ctx, adjustment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStockAdjustment", reflect.TypeOf((*MockInventoryRepository)(nil).CreateStockAdjustment), ctx, adjustment)
}

// CreateStockMovement mocks base method.
func (m *MockInventoryRepository) CreateStockMovement(ctx context.Context, movement *domain.StockMovement) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStockMovement", ctx, movement)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateStockMovement indicates an expected call of CreateStockMovement.
func (mr *MockInventoryRepositoryMockRecorder) CreateStockMovement(ctx, movement interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStockMovement", reflect.TypeOf((*MockInventoryRepository)(nil).CreateStockMovement), ctx, movement)
}

// CreateWarehouse mocks base method.
func (m *MockInventoryRepository) CreateWarehouse(ctx context.Context, warehouse *domain.Warehouse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWarehouse", ctx, warehouse)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateWarehouse indicates an expected call of CreateWarehouse.
func (mr *MockInventoryRepositoryMockRecorder) CreateWarehouse(ctx, warehouse interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWarehouse", reflect.TypeOf((*MockInventoryRepository)(nil).CreateWarehouse), ctx, warehouse)
}

// DeleteInventoryItem mocks base method.
func (m *MockInventoryRepository) DeleteInventoryItem(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventoryItem", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventoryItem indicates an expected call of DeleteInventoryItem.
func (mr *MockInventoryRepositoryMockRecorder) DeleteInventoryItem(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventoryItem", reflect.TypeOf((*MockInventoryRepository)(nil).DeleteInventoryItem), ctx, id)
}

// DeleteWarehouse mocks base method.
func (m *MockInventoryRepository) DeleteWarehouse(ctx context.Context, id uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteWarehouse", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteWarehouse indicates an expected call of DeleteWarehouse.
func (mr *MockInventoryRepositoryMockRecorder) DeleteWarehouse(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteWarehouse", reflect.TypeOf((*MockInventoryRepository)(nil).DeleteWarehouse), ctx, id)
}

// GetInventoryItem mocks base method.
func (m *MockInventoryRepository) GetInventoryItem(ctx context.Context, warehouseID, productID uint) (*domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryItem", ctx, warehouseID, productID)
	ret0, _ := ret[0].(*domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryItem indicates an expected call of GetInventoryItem.
func (mr *MockInventoryRepositoryMockRecorder) GetInventoryItem(ctx, warehouseID, productID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryItem", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventoryItem), ctx, warehouseID, productID)
}

// GetInventoryItemByID mocks base method.
func (m *MockInventoryRepository) GetInventoryItemByID(ctx context.Context, id uint) (*domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryItemByID", ctx, id)
	ret0, _ := ret[0].(*domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryItemByID indicates an expected call of GetInventoryItemByID.
func (mr *MockInventoryRepositoryMockRecorder) GetInventoryItemByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryItemByID", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventoryItemByID), ctx, id)
}

// GetInventoryValue mocks base method.
func (m *MockInventoryRepository) GetInventoryValue(ctx context.Context, warehouseID *uint) (float64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventoryValue", ctx, warehouseID)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventoryValue indicates an expected call of GetInventoryValue.
func (mr *MockInventoryRepositoryMockRecorder) GetInventoryValue(ctx, warehouseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventoryValue", reflect.TypeOf((*MockInventoryRepository)(nil).GetInventoryValue), ctx, warehouseID)
}

// GetLowStockItems mocks base method.
func (m *MockInventoryRepository) GetLowStockItems(ctx context.Context, warehouseID *uint) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLowStockItems", ctx, warehouseID)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLowStockItems indicates an expected call of GetLowStockItems.
func (mr *MockInventoryRepositoryMockRecorder) GetLowStockItems(ctx, warehouseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLowStockItems", reflect.TypeOf((*MockInventoryRepository)(nil).GetLowStockItems), ctx, warehouseID)
}

// GetOutOfStockItems mocks base method.
func (m *MockInventoryRepository) GetOutOfStockItems(ctx context.Context, warehouseID *uint) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOutOfStockItems", ctx, warehouseID)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOutOfStockItems indicates an expected call of GetOutOfStockItems.
func (mr *MockInventoryRepositoryMockRecorder) GetOutOfStockItems(ctx, warehouseID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOutOfStockItems", reflect.TypeOf((*MockInventoryRepository)(nil).GetOutOfStockItems), ctx, warehouseID)
}

// GetStockAdjustments mocks base method.
func (m *MockInventoryRepository) GetStockAdjustments(ctx context.Context, inventoryItemID uint, page, pageSize int) ([]domain.StockAdjustment, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockAdjustments", ctx, inventoryItemID, page, pageSize)
	ret0, _ := ret[0].([]domain.StockAdjustment)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStockAdjustments indicates an expected call of GetStockAdjustments.
func (mr *MockInventoryRepositoryMockRecorder) GetStockAdjustments(ctx, inventoryItemID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockAdjustments", reflect.TypeOf((*MockInventoryRepository)(nil).GetStockAdjustments), ctx, inventoryItemID, page, pageSize)
}

// GetStockLevels mocks base method.
func (m *MockInventoryRepository) GetStockLevels(ctx context.Context, warehouseID *uint, productIDs []uint) ([]domain.InventoryItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockLevels", ctx, warehouseID, productIDs)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStockLevels indicates an expected call of GetStockLevels.
func (mr *MockInventoryRepositoryMockRecorder) GetStockLevels(ctx, warehouseID, productIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockLevels", reflect.TypeOf((*MockInventoryRepository)(nil).GetStockLevels), ctx, warehouseID, productIDs)
}

// GetStockMovements mocks base method.
func (m *MockInventoryRepository) GetStockMovements(ctx context.Context, inventoryItemID uint, page, pageSize int) ([]domain.StockMovement, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockMovements", ctx, inventoryItemID, page, pageSize)
	ret0, _ := ret[0].([]domain.StockMovement)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStockMovements indicates an expected call of GetStockMovements.
func (mr *MockInventoryRepositoryMockRecorder) GetStockMovements(ctx, inventoryItemID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockMovements", reflect.TypeOf((*MockInventoryRepository)(nil).GetStockMovements), ctx, inventoryItemID, page, pageSize)
}

// GetStockMovementsByWarehouse mocks base method.
func (m *MockInventoryRepository) GetStockMovementsByWarehouse(ctx context.Context, warehouseID uint, page, pageSize int) ([]domain.StockMovement, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStockMovementsByWarehouse", ctx, warehouseID, page, pageSize)
	ret0, _ := ret[0].([]domain.StockMovement)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetStockMovementsByWarehouse indicates an expected call of GetStockMovementsByWarehouse.
func (mr *MockInventoryRepositoryMockRecorder) GetStockMovementsByWarehouse(ctx, warehouseID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStockMovementsByWarehouse", reflect.TypeOf((*MockInventoryRepository)(nil).GetStockMovementsByWarehouse), ctx, warehouseID, page, pageSize)
}

// GetWarehouse mocks base method.
func (m *MockInventoryRepository) GetWarehouse(ctx context.Context, id uint) (*domain.Warehouse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWarehouse", ctx, id)
	ret0, _ := ret[0].(*domain.Warehouse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWarehouse indicates an expected call of GetWarehouse.
func (mr *MockInventoryRepositoryMockRecorder) GetWarehouse(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWarehouse", reflect.TypeOf((*MockInventoryRepository)(nil).GetWarehouse), ctx, id)
}

// ListInventoryItems mocks base method.
func (m *MockInventoryRepository) ListInventoryItems(ctx context.Context, warehouseID *uint, page, pageSize int) ([]domain.InventoryItem, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventoryItems", ctx, warehouseID, page, pageSize)
	ret0, _ := ret[0].([]domain.InventoryItem)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListInventoryItems indicates an expected call of ListInventoryItems.
func (mr *MockInventoryRepositoryMockRecorder) ListInventoryItems(ctx, warehouseID, page, pageSize interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventoryItems", reflect.TypeOf((*MockInventoryRepository)(nil).ListInventoryItems), ctx, warehouseID, page, pageSize)
}

// ListWarehouses mocks base method.
func (m *MockInventoryRepository) ListWarehouses(ctx context.Context, page, pageSize int, search string) ([]domain.Warehouse, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWarehouses", ctx, page, pageSize, search)
	ret0, _ := ret[0].([]domain.Warehouse)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListWarehouses indicates an expected call of ListWarehouses.
func (mr *MockInventoryRepositoryMockRecorder) ListWarehouses(ctx, page, pageSize, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWarehouses", reflect.TypeOf((*MockInventoryRepository)(nil).ListWarehouses), ctx, page, pageSize, search)
}

// UpdateInventoryItem mocks base method.
func (m *MockInventoryRepository) UpdateInventoryItem(ctx context.Context, item *domain.InventoryItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventoryItem", ctx, item)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventoryItem indicates an expected call of UpdateInventoryItem.
func (mr *MockInventoryRepositoryMockRecorder) UpdateInventoryItem(ctx, item interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventoryItem", reflect.TypeOf((*MockInventoryRepository)(nil).UpdateInventoryItem), ctx, item)
}

// UpdateWarehouse mocks base method.
func (m *MockInventoryRepository) UpdateWarehouse(ctx context.Context, warehouse *domain.Warehouse) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateWarehouse", ctx, warehouse)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateWarehouse indicates an expected call of UpdateWarehouse.
func (mr *MockInventoryRepositoryMockRecorder) UpdateWarehouse(ctx, warehouse interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateWarehouse", reflect.TypeOf((*MockInventoryRepository)(nil).UpdateWarehouse), ctx, warehouse)
}
