package auth

import (
	"context"
	"net/http"
	"net/url"
	"strings"

	"github.com/ory/fosite"
	oauthusecase "github.com/pmaojo/kthulu-go/backend/internal/modules/oauthsso/usecase"
)

// SSOLogin orchestrates an OAuth SSO login flow using the provided use case.
// It first initiates the authorization step and then exchanges the authorization
// code for tokens. The returned map contains the tokens as generated by fosite.
func SSOLogin(ctx context.Context, uc *oauthusecase.OAuthUseCase, r *http.Request) (map[string]any, error) {
	code, err := uc.Authorize(ctx, r, &fosite.DefaultSession{})
	if err != nil {
		return nil, err
	}

	form := url.Values{}
	form.Set("grant_type", "authorization_code")
	form.Set("code", code)

	tokenReq, err := http.NewRequestWithContext(ctx, http.MethodPost, "/oauth/token", strings.NewReader(form.Encode()))
	if err != nil {
		return nil, err
	}
	tokenReq.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := uc.Token(ctx, tokenReq, &fosite.DefaultSession{})
	if err != nil {
		return nil, err
	}
	return resp, nil
}
