package cmd

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"text/tabwriter"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/pmaojo/kthulu-go/cmd/kthulu/internal/blueprint"
)

func newPlanCmd() *cobra.Command {
	var (
		planTemplate string
		planFeatures []string
		planOutput   string
	)

	cmd := &cobra.Command{
		Use:   "plan [name]",
		Short: "📋 Plan a new project configuration",
		Long: `Generate a project blueprint that describes your application's architecture.
This blueprint can be reviewed, modified, and then used to create the project.

Examples:
  kthulu plan my-app --template=microservice
  kthulu plan my-store --template=ecommerce --features=payment,inventory`,
		Args: cobra.MaximumNArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 {
				return cmd.Help()
			}
			return runPlanProject(cmd, args, planTemplate, planFeatures, planOutput)
		},
	}

	cmd.Flags().StringVarP(&planTemplate, "template", "t", "microservice", "Project template")
	cmd.Flags().StringSliceVarP(&planFeatures, "features", "f", []string{}, "Features/modules")
	cmd.Flags().StringVarP(&planOutput, "output", "o", "kthulu-plan.yaml", "Output file for the plan")

	return cmd
}

var planCmd = newPlanCmd()

// Requirements subcommands
var planReqCmd = &cobra.Command{
	Use:   "req",
	Short: "Manage project requirements",
}

var planReqAddCmd = &cobra.Command{
	Use:   "add [title]",
	Short: "Add a new requirement",
	Args:  cobra.ExactArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		return runPlanReqAdd(cmd, args)
	},
}

var planReqListCmd = &cobra.Command{
	Use:   "list",
	Short: "List all requirements",
	RunE: func(cmd *cobra.Command, args []string) error {
		return runPlanReqList(cmd, args)
	},
}

func init() {
	// Plan command
	rootCmd.AddCommand(planCmd)

	// Requirement subcommands
	planCmd.AddCommand(planReqCmd)
	planReqCmd.AddCommand(planReqAddCmd)
	planReqCmd.AddCommand(planReqListCmd)

	// Flags for req commands
	planReqCmd.PersistentFlags().StringP("file", "f", "kthulu-plan.yaml", "Plan file to modify")

	planReqAddCmd.Flags().String("desc", "", "Description of the requirement")
	planReqAddCmd.Flags().String("priority", "Medium", "Priority (High, Medium, Low)")
}

func runPlanProject(cmd *cobra.Command, args []string, template string, features []string, output string) error {
	projectName := args[0]
	fmt.Printf("📋 Planning project: %s\n", projectName)

	// Create a default blueprint based on flags
	bp := blueprint.ProjectBlueprint{
		Name:        projectName,
		Description: "Generated by Kthulu Planner",
		Template:    template,
		Features:    features,
		Modules:     make(map[string]blueprint.ModuleConfig),
		// Defaults
		Database: "postgres",
		Frontend: "react",
		Auth:     "jwt",
	}

	// Refine defaults based on template
	switch template {
	case "microservice":
		bp.Database = "sqlite"
		bp.Frontend = "none"
	case "ecommerce":
		bp.Features = append(bp.Features, "product", "cart", "order")
	}

	// Remove duplicate features
	bp.Features = uniqueStrings(bp.Features)

	// Serialize to YAML
	if err := saveBlueprint(output, &bp); err != nil {
		return err
	}

	// Read content back to display (or just marshal again)
	data, _ := yaml.Marshal(&bp)

	fmt.Printf("\n✅ Plan generated at %s\n", output)
	fmt.Println("\n📄 Content:")
	fmt.Println(string(data))
	fmt.Println("\n🚀 Next steps:")
	fmt.Printf("   1. Review and edit %s\n", output)
	fmt.Printf("   2. Run 'kthulu create %s --from-plan=%s' (Coming soon)\n", projectName, output)

	return nil
}

func runPlanReqAdd(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")
	desc, _ := cmd.Flags().GetString("desc")
	priority, _ := cmd.Flags().GetString("priority")
	title := args[0]

	// Validate priority
	validPriorities := map[string]bool{
		"High":   true,
		"Medium": true,
		"Low":    true,
	}

	// Normalize priority
	normalizedPriority := strings.Title(strings.ToLower(priority))
	if !validPriorities[normalizedPriority] {
		return fmt.Errorf("invalid priority: %s. Must be High, Medium, or Low", priority)
	}

	bp, err := loadBlueprint(file)
	if err != nil {
		return err
	}

	// Calculate next ID
	nextID := 1
	for _, r := range bp.Requirements {
		if strings.HasPrefix(r.ID, "REQ-") {
			idNum, err := strconv.Atoi(strings.TrimPrefix(r.ID, "REQ-"))
			if err == nil && idNum >= nextID {
				nextID = idNum + 1
			}
		}
	}

	req := blueprint.NewRequirement(title, desc, normalizedPriority, fmt.Sprintf("REQ-%d", nextID))
	bp.Requirements = append(bp.Requirements, req)

	if err := saveBlueprint(file, bp); err != nil {
		return err
	}

	fmt.Printf("✅ Requirement added: %s (%s)\n", req.ID, req.Title)
	return nil
}

func runPlanReqList(cmd *cobra.Command, args []string) error {
	file, _ := cmd.Flags().GetString("file")

	bp, err := loadBlueprint(file)
	if err != nil {
		return err
	}

	if len(bp.Requirements) == 0 {
		fmt.Println("No requirements found.")
		return nil
	}

	fmt.Printf("📋 Requirements for %s:\n", bp.Name)

	w := tabwriter.NewWriter(os.Stdout, 0, 0, 2, ' ', 0)
	fmt.Fprintln(w, "ID\tTitle\tPriority\tStatus")
	fmt.Fprintln(w, "--\t-----\t--------\t------")

	for _, req := range bp.Requirements {
		fmt.Fprintf(w, "%s\t%s\t%s\t%s\n", req.ID, req.Title, req.Priority, req.Status)
	}
	w.Flush()

	return nil
}

// Helpers

func loadBlueprint(filename string) (*blueprint.ProjectBlueprint, error) {
	data, err := os.ReadFile(filename)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("plan file '%s' not found. Run 'kthulu plan [name]' first", filename)
		}
		return nil, fmt.Errorf("failed to read plan file: %w", err)
	}

	var bp blueprint.ProjectBlueprint
	if err := yaml.Unmarshal(data, &bp); err != nil {
		return nil, fmt.Errorf("failed to parse plan file: %w", err)
	}

	return &bp, nil
}

func saveBlueprint(filename string, bp *blueprint.ProjectBlueprint) error {
	data, err := yaml.Marshal(bp)
	if err != nil {
		return fmt.Errorf("failed to marshal plan: %w", err)
	}

	if err := os.WriteFile(filename, data, 0644); err != nil {
		return fmt.Errorf("failed to write plan file: %w", err)
	}

	return nil
}

func uniqueStrings(input []string) []string {
	keys := make(map[string]bool)
	list := []string{}
	for _, entry := range input {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}
	return list
}
