package cmd

import (
	"fmt"
	"os"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

// ProjectBlueprint represents the desired state of a project
type ProjectBlueprint struct {
	Name        string   `yaml:"name"`
	Description string   `yaml:"description"`
	Template    string   `yaml:"template"`
	Features    []string `yaml:"features"`
	Database    string   `yaml:"database"`
	Frontend    string   `yaml:"frontend"`
	Auth        string   `yaml:"auth"`
	Modules     []string `yaml:"modules,omitempty"`
}

func newPlanCmd() *cobra.Command {
	var (
		planTemplate string
		planFeatures []string
		planOutput   string
	)

	cmd := &cobra.Command{
		Use:   "plan [name]",
		Short: "📋 Plan a new project configuration",
		Long: `Generate a project blueprint that describes your application's architecture.
This blueprint can be reviewed, modified, and then used to create the project.

Examples:
  kthulu plan my-app --template=microservice
  kthulu plan my-store --template=ecommerce --features=payment,inventory`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			return runPlanProject(cmd, args, planTemplate, planFeatures, planOutput)
		},
	}

	cmd.Flags().StringVarP(&planTemplate, "template", "t", "microservice", "Project template")
	cmd.Flags().StringSliceVarP(&planFeatures, "features", "f", []string{}, "Features/modules")
	cmd.Flags().StringVarP(&planOutput, "output", "o", "kthulu-plan.yaml", "Output file for the plan")

	return cmd
}

var planCmd = newPlanCmd()

func init() {
	// Note: We don't add this to rootCmd in init() because we want to keep it experimental/optional for now
	// or user can manually enable it. But to fulfill the request of "Intelligent Flow",
	// we should probably expose it.
	rootCmd.AddCommand(planCmd)
}

func runPlanProject(cmd *cobra.Command, args []string, template string, features []string, output string) error {
	projectName := args[0]
	fmt.Printf("📋 Planning project: %s\n", projectName)

	// Create a default blueprint based on flags
	blueprint := ProjectBlueprint{
		Name:        projectName,
		Description: "Generated by Kthulu Planner",
		Template:    template,
		Features:    features,
		// Defaults
		Database: "postgres",
		Frontend: "react",
		Auth:     "jwt",
	}

	// Refine defaults based on template
	switch template {
	case "microservice":
		blueprint.Database = "sqlite"
		blueprint.Frontend = "none"
	case "ecommerce":
		blueprint.Features = append(blueprint.Features, "product", "cart", "order")
	}

	// Remove duplicate features
	blueprint.Features = uniqueStrings(blueprint.Features)

	// Serialize to YAML
	data, err := yaml.Marshal(&blueprint)
	if err != nil {
		return fmt.Errorf("failed to marshal plan: %w", err)
	}

	// Write to file
	if err := os.WriteFile(output, data, 0644); err != nil {
		return fmt.Errorf("failed to write plan file: %w", err)
	}

	fmt.Printf("\n✅ Plan generated at %s\n", output)
	fmt.Println("\n📄 Content:")
	fmt.Println(string(data))
	fmt.Println("\n🚀 Next steps:")
	fmt.Printf("   1. Review and edit %s\n", output)
	fmt.Printf("   2. Run 'kthulu create %s --from-plan=%s' (Coming soon)\n", projectName, output)

	return nil
}

func uniqueStrings(input []string) []string {
	keys := make(map[string]bool)
	list := []string{}
	for _, entry := range input {
		if _, value := keys[entry]; !value {
			keys[entry] = true
			list = append(list, entry)
		}
	}
	return list
}
