package generator

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/pmaojo/kthulu-go/internal/adapters/cli/parser"
	"github.com/pmaojo/kthulu-go/internal/resolver"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarkGenerated_CommentSyntaxPerFileType(t *testing.T) {
	cases := []struct {
		path, content, want string
	}{
		{"internal/x/x.go", "package x\n", "// Code generated by kthulu. DO NOT EDIT.\n\npackage x\n"},
		{"internal/views/a.templ", "package views\n", "// Code generated by kthulu. DO NOT EDIT.\npackage views\n"},
		{".github/workflows/ci.yaml", "name: ci\n", "# Code generated by kthulu. DO NOT EDIT.\nname: ci\n"},
		{"Makefile", "build:\n", "# Code generated by kthulu. DO NOT EDIT.\nbuild:\n"},
		{"Dockerfile", "FROM x\n", "# Code generated by kthulu. DO NOT EDIT.\nFROM x\n"},
		{"migrations/1_x.sql", "CREATE TABLE x();\n", "-- Code generated by kthulu. DO NOT EDIT.\nCREATE TABLE x();\n"},
		{"scripts/build.sh", "#!/bin/bash\nset -e\n", "#!/bin/bash\n# Code generated by kthulu. DO NOT EDIT.\nset -e\n"},
	}
	for _, c := range cases {
		got := MarkGenerated(c.path, c.content)
		assert.Equal(t, c.want, got, c.path)
		assert.True(t, HasGeneratedHeader(got), c.path)
		assert.Equal(t, got, MarkGenerated(c.path, got), "marking must be idempotent: %s", c.path)
	}
}

func TestMarkGenerated_SkipsUserOwnedAndCommentlessFiles(t *testing.T) {
	for _, p := range []string{"go.mod", "README.md", "configs/app.yaml", "internal/cli/root.go", "internal/tools/tools.go", "vercel.json"} {
		assert.Equal(t, "content\n", MarkGenerated(p, "content\n"), p)
	}
}

func TestMergeHoles_PreservesHandWrittenBodiesByName(t *testing.T) {
	fresh := `// Code generated by kthulu. DO NOT EDIT.
func A() {
	// vord:hole a
	// placeholder a
	// vord:end-hole
}
func B() {
	// vord:hole b
	// placeholder b
	// vord:end-hole
}
func C() {
	// vord:hole c
	// placeholder c
	// vord:end-hole
}
`
	existing := `// Code generated by kthulu. DO NOT EDIT.
func B() {
	// vord:hole b
	doB()
	doMoreB()
	// vord:end-hole
}
func A() {
	// HAND EDIT OUTSIDE A HOLE
	// vord:hole a
	doA()
	// vord:end-hole
}
func Gone() {
	// vord:hole gone
	lost()
	// vord:end-hole
}
`
	merged, dropped := MergeHoles(fresh, existing)
	assert.Contains(t, merged, "\t// vord:hole a\n\tdoA()\n\t// vord:end-hole\n")
	assert.Contains(t, merged, "\t// vord:hole b\n\tdoB()\n\tdoMoreB()\n\t// vord:end-hole\n")
	assert.Contains(t, merged, "// placeholder c", "a hole new to the template keeps its placeholder")
	assert.NotContains(t, merged, "placeholder a")
	assert.NotContains(t, merged, "HAND EDIT OUTSIDE", "content outside holes is regenerated")
	assert.True(t, strings.Index(merged, "func A") < strings.Index(merged, "func B"), "layout follows the fresh template")
	assert.Equal(t, []string{"gone"}, dropped)

	// Merging is stable: regenerating again changes nothing.
	again, _ := MergeHoles(fresh, merged)
	assert.Equal(t, merged, again)
}

func TestWriteGeneratedFile_RegenerationKeepsHoles(t *testing.T) {
	gen := newMarkerTestGenerator()
	gen.SetConfig(&GeneratorConfig{ProjectName: "shop", ProjectModule: "github.com/example/shop", Database: "sqlite"})

	files, _, err := gen.GenerateBackendModule("orders", []string{"total:int"}, "internal/modules", "orders", false)
	require.NoError(t, err)
	service := files["core/orders_service.go"]
	require.NotEmpty(t, service)

	path := filepath.Join(t.TempDir(), "orders_service.go")
	require.NoError(t, WriteGeneratedFile(path, service, 0o644))

	// The user fills a hole and also (wrongly) edits generated code.
	onDisk, err := os.ReadFile(path)
	require.NoError(t, err)
	edited := strings.Replace(string(onDisk),
		"\t// vord:hole orders-service-create\n\t// Add business logic here\n",
		"\t// vord:hole orders-service-create\n\tif entity.Total > 1000 {\n\t\treturn ErrTooBig\n\t}\n", 1)
	require.NotEqual(t, string(onDisk), edited, "the create hole must exist")
	edited = strings.Replace(edited, "return s.repo.Delete(id)", "return nil // hacked", 1)
	require.NoError(t, os.WriteFile(path, []byte(edited), 0o644))

	// Regenerate.
	files, _, err = gen.GenerateBackendModule("orders", []string{"total:int"}, "internal/modules", "orders", false)
	require.NoError(t, err)
	require.NoError(t, WriteGeneratedFile(path, files["core/orders_service.go"], 0o644))

	out, err := os.ReadFile(path)
	require.NoError(t, err)
	got := string(out)
	assert.True(t, HasGeneratedHeader(got))
	assert.Contains(t, got, "if entity.Total > 1000 {\n\t\treturn ErrTooBig\n\t}", "hand-written hole content survives regeneration")
	assert.Contains(t, got, "return s.repo.Delete(id)", "edits outside holes are regenerated")
	assert.NotContains(t, got, "hacked")
	assert.Equal(t, 2, strings.Count(got, "// Add business logic here"), "the update and delete holes, untouched, keep their placeholder")
}

func newMarkerTestGenerator() *TemplateGenerator {
	return NewTemplateGenerator(resolver.NewDependencyResolver(&parser.ProjectAnalysis{
		Modules:      make(map[string]*parser.Module),
		Dependencies: []parser.Dependency{},
	}))
}

// Every file `kthulu create` produces is either marked as generated or is
// one of the deliberately user-owned (or comment-less) files, and the
// templates' placeholders for hand-written logic are holes.
func TestGenerateProject_MarksGeneratedFilesAndHoles(t *testing.T) {
	gen := newMarkerTestGenerator()
	structure, err := gen.GenerateProject(&GeneratorConfig{
		ProjectName:   "shop",
		ProjectModule: "github.com/example/shop",
		TemplateType:  "server",
		Database:      "sqlite",
		Auth:          "jwt",
		Frontend:      "templ",
		Features:      []string{"auth", "user", "product", "queues", "mail", "storage", "cache"},
		CustomValues:  map[string]string{"module_path": "github.com/example/shop"},
	})
	require.NoError(t, err)

	unmarked := map[string]bool{}
	for _, f := range structure.Files {
		if HasGeneratedHeader(f.Content) {
			assert.Equal(t, 1, strings.Count(f.Content, GeneratedNotice), "single header in %s", f.Path)
			continue
		}
		unmarked[f.Path] = true
	}
	assert.Equal(t, map[string]bool{
		"go.mod":           true,
		"README.md":        true,
		"configs/app.yaml": true,
		"vercel.json":      true,
		"internal/infrastructure/static/dist/index.html": true,
	}, unmarked, "only user-owned or comment-less files may lack the generated header")

	// Every hole is well-formed, and names are unique per file.
	for _, f := range structure.Files {
		starts := strings.Count(f.Content, HoleStartMarker+" ")
		holes := ParseHoles(f.Content)
		assert.Equal(t, starts, len(holes), "unbalanced hole markers in %s", f.Path)
		seen := map[string]bool{}
		for _, h := range holes {
			assert.False(t, seen[h.Name], "duplicate hole %q in %s", h.Name, f.Path)
			seen[h.Name] = true
		}
	}

	holeNames := func(path string) []string {
		var names []string
		for _, h := range ParseHoles(findFile(t, structure, path)) {
			names = append(names, h.Name)
		}
		return names
	}
	assert.Equal(t, []string{"product-service-imports", "product-service-create", "product-service-update", "product-service-delete"},
		holeNames("internal/modules/product/core/product_service.go"))
	assert.Contains(t, findFile(t, structure, "internal/modules/product/core/product_service.go"),
		"// vord:hole product-service-create\n\t// Add business logic here\n\t// vord:end-hole")
	assert.Equal(t, []string{"jobs-welcome-email"}, holeNames("internal/jobs/jobs.go"))
	assert.Contains(t, holeNames("internal/infrastructure/mail/mailer.go"), "mail-ses")
	assert.Contains(t, holeNames("internal/infrastructure/storage/storage.go"), "storage-s3")
	assert.Contains(t, holeNames("internal/infrastructure/cache/cache.go"), "cache-redis")
	assert.Equal(t, []string{"automigrate-models"}, holeNames("internal/infrastructure/database/automigrate.go"))

	// The header keeps Go files' package doc comment intact.
	assert.True(t, strings.HasPrefix(findFile(t, structure, "pkg/bootstrap/app.go"),
		"// Code generated by kthulu. DO NOT EDIT.\n\n"))
}

func TestGenerateProject_CLIAndMCPRootFilesStayUserOwned(t *testing.T) {
	for _, tmpl := range []string{"cli", "mcp"} {
		gen := newMarkerTestGenerator()
		structure, err := gen.GenerateProject(&GeneratorConfig{
			ProjectName:   "tool",
			ProjectModule: "github.com/example/tool",
			TemplateType:  tmpl,
			CustomValues:  map[string]string{"module_path": "github.com/example/tool"},
		})
		require.NoError(t, err)
		for _, f := range structure.Files {
			assert.Equal(t, !IsUserOwnedPath(f.Path), HasGeneratedHeader(f.Content), "%s: %s", tmpl, f.Path)
		}
		assert.True(t, HasGeneratedHeader(findFile(t, structure, "cmd/tool/main.go")), tmpl)
	}
}
