package generator

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// Generated-code markers.
//
// Every file kthulu derives entirely from the plan and its templates starts
// with a "Code generated by kthulu. DO NOT EDIT." header (Go's standard form,
// in the file's own comment syntax), so tooling and guardrails can tell
// generated code apart from hand-written code. Regions meant for hand-written
// logic inside such files are delimited by
//
//	// vord:hole <name>
//	...hand-written code...
//	// vord:end-hole
//
// Everything outside the holes, marker lines included, is owned by kthulu
// and is rebuilt on regeneration; the content of each hole is carried over
// by name (see MergeHoles).

const (
	// GeneratedNotice is the text of the generated-file header, without
	// comment delimiters.
	GeneratedNotice = "Code generated by kthulu. DO NOT EDIT."

	// HoleStartMarker opens a hand-editable region; it is followed by the
	// region's name.
	HoleStartMarker = "vord:hole"
	// HoleEndMarker closes the region opened by the last HoleStartMarker.
	HoleEndMarker = "vord:end-hole"

	// headerScanLines is how far into a file the header is looked for.
	headerScanLines = 10
)

var holeStartRe = regexp.MustCompile(`vord:hole\s+([A-Za-z0-9_.\-]+)`)

// userOwnedPaths are files kthulu scaffolds once for the user to own and
// edit freely; they never get the generated header.
var userOwnedPaths = map[string]bool{
	FileGoMod:          true, // edited by `go get` / `go mod tidy`
	"go.sum":           true,
	FileReadme:         true,
	"configs/app.yaml": true, // secrets and per-environment tuning
	// CLI template: the root command is a starting point for the user's CLI.
	"internal/cli/root.go": true,
	// MCP template: the tools package and its example UI are where the
	// user defines their own tools.
	"internal/tools/tools.go":          true,
	"internal/tools/ui/dashboard.html": true,
	// Build output placeholder, replaced by the frontend build.
	"internal/infrastructure/static/dist/index.html": true,
}

// IsUserOwnedPath reports whether the file at relPath (relative to the
// project root) is meant to be owned and edited by the user, and so must not
// be marked as generated.
func IsUserOwnedPath(relPath string) bool {
	return userOwnedPaths[filepath.ToSlash(filepath.Clean(relPath))]
}

// generatedHeaderLine returns the header line for path in that file type's
// comment syntax, or "" when the format has no comments (e.g. JSON).
func generatedHeaderLine(path string) string {
	base := filepath.Base(path)
	switch base {
	case "Makefile", "Dockerfile", ".gitignore", ".dockerignore":
		return "# " + GeneratedNotice
	}
	switch strings.ToLower(filepath.Ext(base)) {
	case ".go", ".templ", ".mod", ".js", ".ts", ".css":
		return "// " + GeneratedNotice
	case ".yaml", ".yml", ".sh", ".toml", ".env", ".feature", ".py":
		return "# " + GeneratedNotice
	case ".sql":
		return "-- " + GeneratedNotice
	case ".html", ".md", ".xml":
		return "<!-- " + GeneratedNotice + " -->"
	}
	return ""
}

// HasGeneratedHeader reports whether content carries a generated-code header
// ("Code generated" and "DO NOT EDIT" on one line within its first lines).
func HasGeneratedHeader(content string) bool {
	lines := strings.SplitN(content, "\n", headerScanLines+1)
	if len(lines) > headerScanLines {
		lines = lines[:headerScanLines]
	}
	for _, l := range lines {
		if strings.Contains(l, "Code generated") && strings.Contains(l, "DO NOT EDIT") {
			return true
		}
	}
	return false
}

// MarkGenerated returns content with the generated-code header for path
// added, unless the file is user-owned, its format cannot carry a comment,
// or it already has one. A leading shebang line is kept first.
func MarkGenerated(path, content string) string {
	if content == "" || IsUserOwnedPath(path) || HasGeneratedHeader(content) {
		return content
	}
	header := generatedHeaderLine(path)
	if header == "" {
		return content
	}

	sep := "\n"
	if strings.HasPrefix(header, "//") && strings.HasSuffix(path, ".go") {
		// Keep the header off the package doc comment.
		sep = "\n\n"
	}

	if strings.HasPrefix(content, "#!") {
		nl := strings.IndexByte(content, '\n')
		if nl < 0 {
			return content + "\n" + header + "\n"
		}
		return content[:nl+1] + header + "\n" + content[nl+1:]
	}
	return header + sep + content
}

// markStructure adds the generated header to every file in structure.
func markStructure(structure *ProjectStructure) {
	for i := range structure.Files {
		structure.Files[i].Content = MarkGenerated(structure.Files[i].Path, structure.Files[i].Content)
	}
}

// Hole is one hand-editable region of a generated file.
type Hole struct {
	Name string
	// Body is the region's content between its marker lines, each line
	// with its trailing newline.
	Body string
}

// holeName returns the name of the hole a line opens, or "".
func holeName(line string) string {
	if strings.Contains(line, HoleEndMarker) {
		return ""
	}
	if m := holeStartRe.FindStringSubmatch(line); m != nil {
		return m[1]
	}
	return ""
}

// ParseHoles returns the well-formed holes in content, in order. A hole
// left unterminated is ignored.
func ParseHoles(content string) []Hole {
	var holes []Hole
	var cur *Hole
	var body strings.Builder
	for _, line := range strings.SplitAfter(content, "\n") {
		if cur == nil {
			if name := holeName(line); name != "" {
				cur = &Hole{Name: name}
				body.Reset()
			}
			continue
		}
		if strings.Contains(line, HoleEndMarker) {
			cur.Body = body.String()
			holes = append(holes, *cur)
			cur = nil
			continue
		}
		body.WriteString(line)
	}
	return holes
}

// MergeHoles returns fresh (newly generated content) with the body of every
// hole replaced by the body of the same-named hole in existing (the file as
// it is on disk). Holes new to fresh keep their generated placeholder.
// dropped lists holes of existing that fresh no longer has, whose content
// is therefore not carried over.
func MergeHoles(fresh, existing string) (merged string, dropped []string) {
	old := make(map[string]string)
	for _, h := range ParseHoles(existing) {
		if _, dup := old[h.Name]; !dup {
			old[h.Name] = h.Body
		}
	}
	if len(old) == 0 {
		return fresh, nil
	}

	// Only replace holes that are well-formed in fresh.
	wellFormed := make(map[string]bool)
	for _, h := range ParseHoles(fresh) {
		wellFormed[h.Name] = true
	}

	var out strings.Builder
	used := make(map[string]bool)
	inHole, replacing := false, false
	for _, line := range strings.SplitAfter(fresh, "\n") {
		if !inHole {
			out.WriteString(line)
			if name := holeName(line); name != "" {
				inHole = true
				body, ok := old[name]
				replacing = ok && wellFormed[name] && !used[name]
				if replacing {
					used[name] = true
					out.WriteString(body)
				}
			}
			continue
		}
		if strings.Contains(line, HoleEndMarker) {
			inHole, replacing = false, false
			out.WriteString(line)
			continue
		}
		if !replacing {
			out.WriteString(line)
		}
	}

	for _, h := range ParseHoles(existing) {
		if !used[h.Name] && !contains(dropped, h.Name) {
			dropped = append(dropped, h.Name)
		}
	}
	return out.String(), dropped
}

// WriteGeneratedFile writes content to path, carrying over the content of
// every hole of the file already at path (if any) into the same-named hole
// of content. Use it wherever kthulu overwrites a file it generated before.
func WriteGeneratedFile(path, content string, perm os.FileMode) error {
	existing, err := os.ReadFile(path)
	switch {
	case err == nil:
		var dropped []string
		content, dropped = MergeHoles(content, string(existing))
		if len(dropped) > 0 {
			fmt.Printf("  ⚠️  %s: hand-written hole(s) %s no longer exist in the regenerated file; their content was not kept\n",
				path, strings.Join(dropped, ", "))
		}
	case !errors.Is(err, fs.ErrNotExist):
		return fmt.Errorf("failed to read existing %s: %w", path, err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), perm)
}
