// Code generated by kthulu mcp-schema-gen. DO NOT EDIT.
package mcp

// GeneratedToolRegistry maps tool names to their factory functions.
var GeneratedToolRegistry = map[string]func(Executor CommandExecutor, workingDir string) RegisteredTool{
	"add_admin":           NewAddAdminArgsTool,
	"add_component":       NewAddComponentArgsTool,
	"add_module":          NewAddModuleArgsTool,
	"add_recipe":          NewAddRecipeArgsTool,
	"ai":                  NewAiArgsTool,
	"ai_gen-feature":      NewAiGenFeatureArgsTool,
	"ai_gen-steps":        NewAiGenStepsArgsTool,
	"ai_optimize":         NewAiOptimizeArgsTool,
	"ai_review":           NewAiReviewArgsTool,
	"ai_scaffold":         NewAiScaffoldArgsTool,
	"analyze":             NewAnalyzeArgsTool,
	"audit":               NewAuditArgsTool,
	"bdd_features":        NewBddFeaturesArgsTool,
	"bdd_run":             NewBddRunArgsTool,
	"claude":              NewClaudeArgsTool,
	"coder":               NewCoderArgsTool,
	"compile":             NewCompileArgsTool,
	"console":             NewConsoleArgsTool,
	"create":              NewCreateArgsTool,
	"debug":               NewDebugArgsTool,
	"deploy":              NewDeployArgsTool,
	"dev":                 NewDevArgsTool,
	"doc":                 NewDocArgsTool,
	"doctor":              NewDoctorArgsTool,
	"gemini":              NewGeminiArgsTool,
	"generate":            NewGenerateArgsTool,
	"marketplace_install": NewMarketplaceInstallArgsTool,
	"marketplace_list":    NewMarketplaceListArgsTool,
	"migrate_create":      NewMigrateCreateArgsTool,
	"migrate_diff":        NewMigrateDiffArgsTool,
	"migrate_down":        NewMigrateDownArgsTool,
	"migrate_reset":       NewMigrateResetArgsTool,
	"migrate_status":      NewMigrateStatusArgsTool,
	"migrate_up":          NewMigrateUpArgsTool,
	"migrate_validate":    NewMigrateValidateArgsTool,
	"migrate_version":     NewMigrateVersionArgsTool,
	"plan":                NewPlanArgsTool,
	"plan_req_add":        NewPlanReqAddArgsTool,
	"plan_req_list":       NewPlanReqListArgsTool,
	"queue_consume":       NewQueueConsumeArgsTool,
	"queue_publish":       NewQueuePublishArgsTool,
	"status":              NewStatusArgsTool,
	"upgrade":             NewUpgradeArgsTool,
}

// AddAdminArgs defines arguments for the add_admin command.
type AddAdminArgs struct {
}

// NewAddAdminArgsTool creates a RegisteredTool for add_admin.
func NewAddAdminArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AddAdminArgs](
		"add_admin",
		"Add a full Admin Dashboard module\nUsage: kthulu add admin",
		[]string{
			"add",
			"admin",
		},
		executor,
		workingDir,
	)
}

// AddComponentArgs defines arguments for the add_component command.
type AddComponentArgs struct {
	Type          string `json:"type,omitempty" jsonschema:"description=Positional argument: type" kthulu:"pos,index=0"`
	Name          string `json:"name,omitempty" jsonschema:"description=Positional argument: name" kthulu:"pos,index=1"`
	Module        string `json:"module,omitempty" jsonschema:"description=Target module (auto-detected if empty)" kthulu:"flag,name=module"`
	WithMigration bool   `json:"with-migration,omitempty" jsonschema:"description=Generate database migration" kthulu:"flag,name=with-migration"`
	WithTests     bool   `json:"with-tests,omitempty" jsonschema:"description=Generate tests" kthulu:"flag,name=with-tests"`
}

// NewAddComponentArgsTool creates a RegisteredTool for add_component.
func NewAddComponentArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AddComponentArgs](
		"add_component",
		"Add a new component to your project\nUsage: kthulu add component [type] [name] [flags]",
		[]string{
			"add",
			"component",
		},
		executor,
		workingDir,
	)
}

// AddModuleArgs defines arguments for the add_module command.
type AddModuleArgs struct {
	Name       string   `json:"name,omitempty" jsonschema:"description=Positional argument: name" kthulu:"pos,index=0"`
	FieldType  []string `json:"field_type,omitempty" jsonschema:"description=Field definitions using name:type[:rules] syntax. Types: string, int, float, bool, time. Validation rules (comma-separated): required, min=N, max=N, email, oneof=a|b|c. Relations: name:belongs_to:module. Example: ["title:string:required,min=2", "score:int:min=0", "played_at:time", "winner:belongs_to:team"]. ALWAYS declare the real fields of the entity — without them the module defaults to a single 'name' field." kthulu:"pos,index=1,variadic"`
	Admin      bool     `json:"admin,omitempty" jsonschema:"description=Generate Admin CRUD pages" kthulu:"flag,name=admin"`
	Compliance string   `json:"compliance,omitempty" jsonschema:"description=Compliance requirements (pci, sox, gdpr)" kthulu:"flag,name=compliance"`
	Force      bool     `json:"force,omitempty" jsonschema:"description=Force add even if conflicts exist" kthulu:"flag,name=force"`
	Prefix     string   `json:"prefix,omitempty" jsonschema:"description=Route prefix (e.g. /api/v1)" kthulu:"flag,name=prefix"`
	Protected  bool     `json:"protected,omitempty" jsonschema:"description=Protect routes with authentication middleware" kthulu:"flag,name=protected"`
	With       []string `json:"with,omitempty" jsonschema:"description=Integration packages (stripe, oauth, etc)" kthulu:"flag,name=with"`
	Yes        bool     `json:"yes,omitempty" jsonschema:"description=Skip confirmation prompts" kthulu:"flag,name=yes"`
}

// NewAddModuleArgsTool creates a RegisteredTool for add_module.
func NewAddModuleArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AddModuleArgs](
		"add_module",
		"Add a new module to your project with optional fields\nUsage: kthulu add module [name] [field:type...] [flags]",
		[]string{
			"add",
			"module",
		},
		executor,
		workingDir,
	)
}

// AddRecipeArgs defines arguments for the add_recipe command.
type AddRecipeArgs struct {
	Name string `json:"name,omitempty" jsonschema:"description=Positional argument: name" kthulu:"pos,index=0"`
}

// NewAddRecipeArgsTool creates a RegisteredTool for add_recipe.
func NewAddRecipeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AddRecipeArgs](
		"add_recipe",
		"Add a complete recipe (stack of modules)\nUsage: kthulu add recipe [name]",
		[]string{
			"add",
			"recipe",
		},
		executor,
		workingDir,
	)
}

// AiArgs defines arguments for the ai command.
type AiArgs struct {
	Prompt string `json:"prompt,omitempty" jsonschema:"description=Positional argument: prompt" kthulu:"pos,index=0"`
}

// NewAiArgsTool creates a RegisteredTool for ai.
func NewAiArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AiArgs](
		"ai",
		"🤖 AI-powered code generation and assistance\nUsage: kthulu ai [prompt]",
		[]string{
			"ai",
		},
		executor,
		workingDir,
	)
}

// AiGenFeatureArgs defines arguments for the ai_gen-feature command.
type AiGenFeatureArgs struct {
	Description string `json:"description,omitempty" jsonschema:"description=Positional argument: description" kthulu:"pos,index=0"`
}

// NewAiGenFeatureArgsTool creates a RegisteredTool for ai_gen-feature.
func NewAiGenFeatureArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AiGenFeatureArgs](
		"ai_gen-feature",
		"Generate a BDD feature file\nUsage: kthulu ai gen-feature [description]",
		[]string{
			"ai",
			"gen-feature",
		},
		executor,
		workingDir,
	)
}

// AiGenStepsArgs defines arguments for the ai_gen-steps command.
type AiGenStepsArgs struct {
	FeatureFile string `json:"feature_file,omitempty" jsonschema:"description=Positional argument: feature_file" kthulu:"pos,index=0"`
}

// NewAiGenStepsArgsTool creates a RegisteredTool for ai_gen-steps.
func NewAiGenStepsArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AiGenStepsArgs](
		"ai_gen-steps",
		"Generate step definitions for a feature\nUsage: kthulu ai gen-steps [feature_file]",
		[]string{
			"ai",
			"gen-steps",
		},
		executor,
		workingDir,
	)
}

// AiOptimizeArgs defines arguments for the ai_optimize command.
type AiOptimizeArgs struct {
	Benchmark bool   `json:"benchmark,omitempty" jsonschema:"description=Run benchmarks before and after optimization" kthulu:"flag,name=benchmark"`
	Target    string `json:"target,omitempty" jsonschema:"description=Optimization target (performance, memory, scalability)" kthulu:"flag,name=target"`
}

// NewAiOptimizeArgsTool creates a RegisteredTool for ai_optimize.
func NewAiOptimizeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AiOptimizeArgs](
		"ai_optimize",
		"⚡ AI-powered performance optimization\nUsage: kthulu ai optimize [flags]",
		[]string{
			"ai",
			"optimize",
		},
		executor,
		workingDir,
	)
}

// AiReviewArgs defines arguments for the ai_review command.
type AiReviewArgs struct {
	Compliance     string `json:"compliance,omitempty" jsonschema:"description=Check compliance (sox, gdpr, pci)" kthulu:"flag,name=compliance"`
	FixAll         bool   `json:"fix-all,omitempty" jsonschema:"description=Fix all detected issues" kthulu:"flag,name=fix-all"`
	FixPerformance bool   `json:"fix-performance,omitempty" jsonschema:"description=Fix performance issues" kthulu:"flag,name=fix-performance"`
	FixSecurity    bool   `json:"fix-security,omitempty" jsonschema:"description=Fix security vulnerabilities" kthulu:"flag,name=fix-security"`
}

// NewAiReviewArgsTool creates a RegisteredTool for ai_review.
func NewAiReviewArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AiReviewArgs](
		"ai_review",
		"📝 AI-powered code review and fixes\nUsage: kthulu ai review [flags]",
		[]string{
			"ai",
			"review",
		},
		executor,
		workingDir,
	)
}

// AiScaffoldArgs defines arguments for the ai_scaffold command.
type AiScaffoldArgs struct {
	Description string `json:"description,omitempty" jsonschema:"description=Positional argument: description" kthulu:"pos,index=0"`
	Output      string `json:"output,omitempty" jsonschema:"description=Output file for the plan" kthulu:"flag,name=output"`
}

// NewAiScaffoldArgsTool creates a RegisteredTool for ai_scaffold.
func NewAiScaffoldArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AiScaffoldArgs](
		"ai_scaffold",
		"🏗️  AI-powered project scaffolding\nUsage: kthulu ai scaffold [description] [flags]",
		[]string{
			"ai",
			"scaffold",
		},
		executor,
		workingDir,
	)
}

// AnalyzeArgs defines arguments for the analyze command.
type AnalyzeArgs struct {
	Dir      string `json:"dir,omitempty" jsonschema:"description=Positional argument: dir" kthulu:"pos,index=0"`
	Format   string `json:"format,omitempty" jsonschema:"description=Graph format: dot, json or yaml" kthulu:"flag,name=format"`
	Graph    bool   `json:"graph,omitempty" jsonschema:"description=Generate and export validation graph" kthulu:"flag,name=graph"`
	Validate bool   `json:"validate,omitempty" jsonschema:"description=Validate graph and report violations" kthulu:"flag,name=validate"`
}

// NewAnalyzeArgsTool creates a RegisteredTool for analyze.
func NewAnalyzeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AnalyzeArgs](
		"analyze",
		"Analyze overrides and extends annotations in the project\nUsage: kthulu analyze [dir] [flags]",
		[]string{
			"analyze",
		},
		executor,
		workingDir,
	)
}

// AuditArgs defines arguments for the audit command.
type AuditArgs struct {
	Compliance   string `json:"compliance,omitempty" jsonschema:"description=Compliance standard (sox, gdpr, pci)" kthulu:"flag,name=compliance"`
	Dependencies bool   `json:"dependencies,omitempty" jsonschema:"description=Check dependency vulnerabilities" kthulu:"flag,name=dependencies"`
	Fix          bool   `json:"fix,omitempty" jsonschema:"description=Automatically fix found issues" kthulu:"flag,name=fix"`
	Security     bool   `json:"security,omitempty" jsonschema:"description=Run security analysis" kthulu:"flag,name=security"`
}

// NewAuditArgsTool creates a RegisteredTool for audit.
func NewAuditArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[AuditArgs](
		"audit",
		"🔍 Enterprise security and compliance auditing\nUsage: kthulu audit [flags]",
		[]string{
			"audit",
		},
		executor,
		workingDir,
	)
}

// BddFeaturesArgs defines arguments for the bdd_features command.
type BddFeaturesArgs struct {
}

// NewBddFeaturesArgsTool creates a RegisteredTool for bdd_features.
func NewBddFeaturesArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[BddFeaturesArgs](
		"bdd_features",
		"List all feature files\nUsage: kthulu bdd features",
		[]string{
			"bdd",
			"features",
		},
		executor,
		workingDir,
	)
}

// BddRunArgs defines arguments for the bdd_run command.
type BddRunArgs struct {
	Filter string `json:"filter,omitempty" jsonschema:"description=Filter scenarios to run" kthulu:"flag,name=filter"`
}

// NewBddRunArgsTool creates a RegisteredTool for bdd_run.
func NewBddRunArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[BddRunArgs](
		"bdd_run",
		"Run BDD scenarios\nUsage: kthulu bdd run [flags]",
		[]string{
			"bdd",
			"run",
		},
		executor,
		workingDir,
	)
}

// ClaudeArgs defines arguments for the claude command.
type ClaudeArgs struct {
}

// NewClaudeArgsTool creates a RegisteredTool for claude.
func NewClaudeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[ClaudeArgs](
		"claude",
		"🤖 Configure and launch Claude CLI with Kthulu superpowers\nUsage: kthulu claude",
		[]string{
			"claude",
		},
		executor,
		workingDir,
	)
}

// CoderArgs defines arguments for the coder command.
type CoderArgs struct {
	Model string `json:"model,omitempty" jsonschema:"description=AI model to use (e.g., gemini-2.5-flash, claude-3-sonnet)" kthulu:"flag,name=model"`
}

// NewCoderArgsTool creates a RegisteredTool for coder.
func NewCoderArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[CoderArgs](
		"coder",
		"🐙 AI-powered coding assistant with a beautiful TUI\nUsage: kthulu coder [flags]",
		[]string{
			"coder",
		},
		executor,
		workingDir,
	)
}

// CompileArgs defines arguments for the compile command.
type CompileArgs struct {
	Out   string `json:"out,omitempty" jsonschema:"description=Output directory" kthulu:"flag,name=out"`
	Watch bool   `json:"watch,omitempty" jsonschema:"description=Watch for changes" kthulu:"flag,name=watch"`
}

// NewCompileArgsTool creates a RegisteredTool for compile.
func NewCompileArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[CompileArgs](
		"compile",
		"Compile overrides and extensions\nUsage: kthulu compile [flags]",
		[]string{
			"compile",
		},
		executor,
		workingDir,
	)
}

// ConsoleArgs defines arguments for the console command.
type ConsoleArgs struct {
	Driver string `json:"driver,omitempty" jsonschema:"description=Database driver override: sqlite, postgres, mysql" kthulu:"flag,name=driver"`
	Dsn    string `json:"dsn,omitempty" jsonschema:"description=Database DSN override (skips auto-discovery)" kthulu:"flag,name=dsn"`
	Exec   string `json:"exec,omitempty" jsonschema:"description=Run a single console command and exit" kthulu:"flag,name=exec"`
}

// NewConsoleArgsTool creates a RegisteredTool for console.
func NewConsoleArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[ConsoleArgs](
		"console",
		"🔮 Interactive database console for your project (tinker equivalent)\nUsage: kthulu console [flags]",
		[]string{
			"console",
		},
		executor,
		workingDir,
	)
}

// CreateArgs defines arguments for the create command.
type CreateArgs struct {
	Name          string   `json:"name,omitempty" jsonschema:"description=Positional argument: name" kthulu:"pos,index=0"`
	Auth          string   `json:"auth,omitempty" jsonschema:"description=Auth type (jwt, oauth, both)" kthulu:"flag,name=auth"`
	Database      string   `json:"database,omitempty" jsonschema:"description=Database type (sqlite, postgres, mysql)" kthulu:"flag,name=database"`
	DryRun        bool     `json:"dry-run,omitempty" jsonschema:"description=Show what would be generated without creating files" kthulu:"flag,name=dry-run"`
	Enterprise    bool     `json:"enterprise,omitempty" jsonschema:"description=Enable enterprise features" kthulu:"flag,name=enterprise"`
	Features      []string `json:"features,omitempty" jsonschema:"description=Comma-separated list of features/modules" kthulu:"flag,name=features"`
	FromPlan      string   `json:"from-plan,omitempty" jsonschema:"description=Create project from plan file" kthulu:"flag,name=from-plan"`
	Frontend      string   `json:"frontend,omitempty" jsonschema:"description=Frontend type: templ (GTH - default), none" kthulu:"flag,name=frontend"`
	Interactive   bool     `json:"interactive,omitempty" jsonschema:"description=Interactive project configuration" kthulu:"flag,name=interactive"`
	ModulePath    string   `json:"module-path,omitempty" jsonschema:"description=Go module path (default: project name)" kthulu:"flag,name=module-path"`
	NoVercel      bool     `json:"no-vercel,omitempty" jsonschema:"description=Skip Vercel deployment files" kthulu:"flag,name=no-vercel"`
	Observability bool     `json:"observability,omitempty" jsonschema:"description=Enable observability stack" kthulu:"flag,name=observability"`
	Output        string   `json:"output,omitempty" jsonschema:"description=Output directory (default: current directory)" kthulu:"flag,name=output"`
	SkipPostgen   bool     `json:"skip-postgen,omitempty" jsonschema:"description=Skip templ generate, go mod tidy and go test after generation (fast mode; default in MCP)" kthulu:"flag,name=skip-postgen"`
	Template      string   `json:"template,omitempty" jsonschema:"description=Project template" kthulu:"flag,name=template"`
}

// NewCreateArgsTool creates a RegisteredTool for create.
func NewCreateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[CreateArgs](
		"create",
		"🚀 Create a new Kthulu project (The easy way)\nUsage: kthulu create [name] [flags]",
		[]string{
			"create",
		},
		executor,
		workingDir,
	)
}

// DebugArgs defines arguments for the debug command.
type DebugArgs struct {
	Cmd       string `json:"cmd,omitempty" jsonschema:"description=Command to run the application (default: auto-detect 'go run ...')" kthulu:"flag,name=cmd"`
	Persist   bool   `json:"persist,omitempty" jsonschema:"description=Persist debug events to disk" kthulu:"flag,name=persist"`
	TestWatch bool   `json:"test-watch,omitempty" jsonschema:"description=Watch tests and display status" kthulu:"flag,name=test-watch"`
}

// NewDebugArgsTool creates a RegisteredTool for debug.
func NewDebugArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[DebugArgs](
		"debug",
		"🐞 Interactive debug daemon and runtime monitor\nUsage: kthulu debug [flags]",
		[]string{
			"debug",
		},
		executor,
		workingDir,
	)
}

// DeployArgs defines arguments for the deploy command.
type DeployArgs struct {
	Cloud     string `json:"cloud,omitempty" jsonschema:"description=Cloud provider (aws, gcp, azure)" kthulu:"flag,name=cloud"`
	Namespace string `json:"namespace,omitempty" jsonschema:"description=Kubernetes namespace" kthulu:"flag,name=namespace"`
	Region    string `json:"region,omitempty" jsonschema:"description=Deployment region" kthulu:"flag,name=region"`
	Scale     string `json:"scale,omitempty" jsonschema:"description=Scaling strategy (auto, manual, fixed)" kthulu:"flag,name=scale"`
}

// NewDeployArgsTool creates a RegisteredTool for deploy.
func NewDeployArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[DeployArgs](
		"deploy",
		"🚀 Zero-config multi-cloud deployment\nUsage: kthulu deploy [flags]",
		[]string{
			"deploy",
		},
		executor,
		workingDir,
	)
}

// DevArgs defines arguments for the dev command.
type DevArgs struct {
}

// NewDevArgsTool creates a RegisteredTool for dev.
func NewDevArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[DevArgs](
		"dev",
		"Start the self-healing development server\nUsage: kthulu dev",
		[]string{
			"dev",
		},
		executor,
		workingDir,
	)
}

// DocArgs defines arguments for the doc command.
type DocArgs struct {
	Diagrams    bool   `json:"diagrams,omitempty" jsonschema:"description=Generate Mermaid architecture diagrams" kthulu:"flag,name=diagrams"`
	Dir         string `json:"dir,omitempty" jsonschema:"description=Directory to search for main.go (default: project root)" kthulu:"flag,name=dir"`
	GeneralInfo string `json:"generalInfo,omitempty" jsonschema:"description=API general info file (default: cmd/server/main.go)" kthulu:"flag,name=generalInfo"`
}

// NewDocArgsTool creates a RegisteredTool for doc.
func NewDocArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[DocArgs](
		"doc",
		"📚 Generate API documentation\nUsage: kthulu doc [flags]",
		[]string{
			"doc",
		},
		executor,
		workingDir,
	)
}

// DoctorArgs defines arguments for the doctor command.
type DoctorArgs struct {
	Verbose bool `json:"verbose,omitempty" jsonschema:"description=Show detailed output for checks" kthulu:"flag,name=verbose"`
}

// NewDoctorArgsTool creates a RegisteredTool for doctor.
func NewDoctorArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[DoctorArgs](
		"doctor",
		"🩺 Diagnose your development environment\nUsage: kthulu doctor [flags]",
		[]string{
			"doctor",
		},
		executor,
		workingDir,
	)
}

// GeminiArgs defines arguments for the gemini command.
type GeminiArgs struct {
}

// NewGeminiArgsTool creates a RegisteredTool for gemini.
func NewGeminiArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[GeminiArgs](
		"gemini",
		"✨ Launch Gemini CLI with Kthulu Superpowers (Context + MCP)\nUsage: kthulu gemini",
		[]string{
			"gemini",
		},
		executor,
		workingDir,
	)
}

// GenerateArgs defines arguments for the generate command.
type GenerateArgs struct {
	Prompt string `json:"prompt,omitempty" jsonschema:"description=Natural language description of what to build" kthulu:"flag,name=prompt"`
}

// NewGenerateArgsTool creates a RegisteredTool for generate.
func NewGenerateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[GenerateArgs](
		"generate",
		"✨ Generate code from natural language prompts\nUsage: kthulu generate [flags]\nExamples:\nkthulu generate --prompt \"I need a blog module\"\n  kthulu generate --prompt \"create a user handler\"\n  kthulu generate --prompt \"add an admin dashboard\"",
		[]string{
			"generate",
		},
		executor,
		workingDir,
	)
}

// MarketplaceInstallArgs defines arguments for the marketplace_install command.
type MarketplaceInstallArgs struct {
	Id   string `json:"id,omitempty" jsonschema:"description=Positional argument: id" kthulu:"pos,index=0"`
	Repo string `json:"repo,omitempty" jsonschema:"description=Path to marketplace repository" kthulu:"flag,name=repo"`
}

// NewMarketplaceInstallArgsTool creates a RegisteredTool for marketplace_install.
func NewMarketplaceInstallArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MarketplaceInstallArgs](
		"marketplace_install",
		"Install a plugin or add a module\nUsage: kthulu marketplace install [id] [flags]",
		[]string{
			"marketplace",
			"install",
		},
		executor,
		workingDir,
	)
}

// MarketplaceListArgs defines arguments for the marketplace_list command.
type MarketplaceListArgs struct {
	Repo string `json:"repo,omitempty" jsonschema:"description=Path to marketplace repository" kthulu:"flag,name=repo"`
	Type string `json:"type,omitempty" jsonschema:"description=Filter by type (starter, module, plugin)" kthulu:"flag,name=type"`
}

// NewMarketplaceListArgsTool creates a RegisteredTool for marketplace_list.
func NewMarketplaceListArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MarketplaceListArgs](
		"marketplace_list",
		"List available items\nUsage: kthulu marketplace list [flags]",
		[]string{
			"marketplace",
			"list",
		},
		executor,
		workingDir,
	)
}

// MigrateCreateArgs defines arguments for the migrate_create command.
type MigrateCreateArgs struct {
	Name string `json:"name,omitempty" jsonschema:"description=Positional argument: name" kthulu:"pos,index=0"`
}

// NewMigrateCreateArgsTool creates a RegisteredTool for migrate_create.
func NewMigrateCreateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateCreateArgs](
		"migrate_create",
		"Create a new migration file\nUsage: kthulu migrate create [name]",
		[]string{
			"migrate",
			"create",
		},
		executor,
		workingDir,
	)
}

// MigrateDiffArgs defines arguments for the migrate_diff command.
type MigrateDiffArgs struct {
	DryRun bool   `json:"dry-run,omitempty" jsonschema:"description=Print the migration instead of writing a file" kthulu:"flag,name=dry-run"`
	Name   string `json:"name,omitempty" jsonschema:"description=Migration name suffix (default schema_diff)" kthulu:"flag,name=name"`
}

// NewMigrateDiffArgsTool creates a RegisteredTool for migrate_diff.
func NewMigrateDiffArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateDiffArgs](
		"migrate_diff",
		"Generate a migration from the gap between your entities and the database\nUsage: kthulu migrate diff [flags]",
		[]string{
			"migrate",
			"diff",
		},
		executor,
		workingDir,
	)
}

// MigrateDownArgs defines arguments for the migrate_down command.
type MigrateDownArgs struct {
}

// NewMigrateDownArgsTool creates a RegisteredTool for migrate_down.
func NewMigrateDownArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateDownArgs](
		"migrate_down",
		"Revert the last migration\nUsage: kthulu migrate down",
		[]string{
			"migrate",
			"down",
		},
		executor,
		workingDir,
	)
}

// MigrateResetArgs defines arguments for the migrate_reset command.
type MigrateResetArgs struct {
}

// NewMigrateResetArgsTool creates a RegisteredTool for migrate_reset.
func NewMigrateResetArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateResetArgs](
		"migrate_reset",
		"Reset database and reapply all migrations\nUsage: kthulu migrate reset",
		[]string{
			"migrate",
			"reset",
		},
		executor,
		workingDir,
	)
}

// MigrateStatusArgs defines arguments for the migrate_status command.
type MigrateStatusArgs struct {
}

// NewMigrateStatusArgsTool creates a RegisteredTool for migrate_status.
func NewMigrateStatusArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateStatusArgs](
		"migrate_status",
		"Show current database version\nUsage: kthulu migrate status",
		[]string{
			"migrate",
			"status",
		},
		executor,
		workingDir,
	)
}

// MigrateUpArgs defines arguments for the migrate_up command.
type MigrateUpArgs struct {
}

// NewMigrateUpArgsTool creates a RegisteredTool for migrate_up.
func NewMigrateUpArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateUpArgs](
		"migrate_up",
		"Apply all pending migrations\nUsage: kthulu migrate up",
		[]string{
			"migrate",
			"up",
		},
		executor,
		workingDir,
	)
}

// MigrateValidateArgs defines arguments for the migrate_validate command.
type MigrateValidateArgs struct {
}

// NewMigrateValidateArgsTool creates a RegisteredTool for migrate_validate.
func NewMigrateValidateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateValidateArgs](
		"migrate_validate",
		"Validate all migrations are correct\nUsage: kthulu migrate validate",
		[]string{
			"migrate",
			"validate",
		},
		executor,
		workingDir,
	)
}

// MigrateVersionArgs defines arguments for the migrate_version command.
type MigrateVersionArgs struct {
	Target string `json:"target,omitempty" jsonschema:"description=Positional argument: target" kthulu:"pos,index=0"`
}

// NewMigrateVersionArgsTool creates a RegisteredTool for migrate_version.
func NewMigrateVersionArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[MigrateVersionArgs](
		"migrate_version",
		"Migrate database to a specific version\nUsage: kthulu migrate version [target]",
		[]string{
			"migrate",
			"version",
		},
		executor,
		workingDir,
	)
}

// PlanArgs defines arguments for the plan command.
type PlanArgs struct {
	Name     string   `json:"name,omitempty" jsonschema:"description=Positional argument: name" kthulu:"pos,index=0"`
	Features []string `json:"features,omitempty" jsonschema:"description=Features/modules" kthulu:"flag,name=features"`
	Output   string   `json:"output,omitempty" jsonschema:"description=Output file for the plan" kthulu:"flag,name=output"`
	Template string   `json:"template,omitempty" jsonschema:"description=Project template" kthulu:"flag,name=template"`
}

// NewPlanArgsTool creates a RegisteredTool for plan.
func NewPlanArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[PlanArgs](
		"plan",
		"📋 Plan a new project configuration\nUsage: kthulu plan [name] [flags]",
		[]string{
			"plan",
		},
		executor,
		workingDir,
	)
}

// PlanReqAddArgs defines arguments for the plan_req_add command.
type PlanReqAddArgs struct {
	Title    string `json:"title,omitempty" jsonschema:"description=Positional argument: title" kthulu:"pos,index=0"`
	Desc     string `json:"desc,omitempty" jsonschema:"description=Description of the requirement" kthulu:"flag,name=desc"`
	Priority string `json:"priority,omitempty" jsonschema:"description=Priority (High, Medium, Low)" kthulu:"flag,name=priority"`
}

// NewPlanReqAddArgsTool creates a RegisteredTool for plan_req_add.
func NewPlanReqAddArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[PlanReqAddArgs](
		"plan_req_add",
		"Add a new requirement\nUsage: kthulu plan req add [title] [flags]",
		[]string{
			"plan",
			"req",
			"add",
		},
		executor,
		workingDir,
	)
}

// PlanReqListArgs defines arguments for the plan_req_list command.
type PlanReqListArgs struct {
}

// NewPlanReqListArgsTool creates a RegisteredTool for plan_req_list.
func NewPlanReqListArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[PlanReqListArgs](
		"plan_req_list",
		"List all requirements\nUsage: kthulu plan req list",
		[]string{
			"plan",
			"req",
			"list",
		},
		executor,
		workingDir,
	)
}

// QueueConsumeArgs defines arguments for the queue_consume command.
type QueueConsumeArgs struct {
	Queue string `json:"queue,omitempty" jsonschema:"description=Positional argument: queue" kthulu:"pos,index=0"`
}

// NewQueueConsumeArgsTool creates a RegisteredTool for queue_consume.
func NewQueueConsumeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[QueueConsumeArgs](
		"queue_consume",
		"Consume messages from a queue\nUsage: kthulu queue consume [queue]",
		[]string{
			"queue",
			"consume",
		},
		executor,
		workingDir,
	)
}

// QueuePublishArgs defines arguments for the queue_publish command.
type QueuePublishArgs struct {
	Queue   string `json:"queue,omitempty" jsonschema:"description=Positional argument: queue" kthulu:"pos,index=0"`
	Message string `json:"message,omitempty" jsonschema:"description=Positional argument: message" kthulu:"pos,index=1"`
}

// NewQueuePublishArgsTool creates a RegisteredTool for queue_publish.
func NewQueuePublishArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[QueuePublishArgs](
		"queue_publish",
		"Publish a message to a queue\nUsage: kthulu queue publish [queue] [message]",
		[]string{
			"queue",
			"publish",
		},
		executor,
		workingDir,
	)
}

// StatusArgs defines arguments for the status command.
type StatusArgs struct {
	Detailed bool `json:"detailed,omitempty" jsonschema:"description=Show detailed information" kthulu:"flag,name=detailed"`
	Modules  bool `json:"modules,omitempty" jsonschema:"description=Focus on module information" kthulu:"flag,name=modules"`
}

// NewStatusArgsTool creates a RegisteredTool for status.
func NewStatusArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[StatusArgs](
		"status",
		"📊 Project health and status overview\nUsage: kthulu status [flags]",
		[]string{
			"status",
		},
		executor,
		workingDir,
	)
}

// UpgradeArgs defines arguments for the upgrade command.
type UpgradeArgs struct {
	DryRun  bool   `json:"dry-run,omitempty" jsonschema:"description=Preview changes without applying" kthulu:"flag,name=dry-run"`
	Version string `json:"version,omitempty" jsonschema:"description=Target version" kthulu:"flag,name=version"`
}

// NewUpgradeArgsTool creates a RegisteredTool for upgrade.
func NewUpgradeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[UpgradeArgs](
		"upgrade",
		"📈 Upgrade framework and dependencies\nUsage: kthulu upgrade [flags]",
		[]string{
			"upgrade",
		},
		executor,
		workingDir,
	)
}
