// Code generated by kthulu mcp-schema-gen. DO NOT EDIT.
package mcp

import (
	"context"
	"fmt"
	"strings"

	mcp_golang "github.com/metoro-io/mcp-golang"
)

// GeneratedToolRegistry maps tool names to their factory functions.
var GeneratedToolRegistry = map[string]func(Executor CommandExecutor, workingDir string) RegisteredTool{
	"add_admin":           NewAddAdminArgsTool,
	"add_component":       NewAddComponentArgsTool,
	"add_module":          NewAddModuleArgsTool,
	"add_recipe":          NewAddRecipeArgsTool,
	"ai":                  NewAiArgsTool,
	"ai_gen-feature":      NewAiGenFeatureArgsTool,
	"ai_gen-steps":        NewAiGenStepsArgsTool,
	"ai_optimize":         NewAiOptimizeArgsTool,
	"ai_review":           NewAiReviewArgsTool,
	"ai_scaffold":         NewAiScaffoldArgsTool,
	"analyze":             NewAnalyzeArgsTool,
	"audit":               NewAuditArgsTool,
	"bdd_features":        NewBddFeaturesArgsTool,
	"bdd_run":             NewBddRunArgsTool,
	"claude":              NewClaudeArgsTool,
	"coder":               NewCoderArgsTool,
	"compile":             NewCompileArgsTool,
	"create":              NewCreateArgsTool,
	"debug":               NewDebugArgsTool,
	"deploy":              NewDeployArgsTool,
	"dev":                 NewDevArgsTool,
	"doc":                 NewDocArgsTool,
	"doctor":              NewDoctorArgsTool,
	"gemini":              NewGeminiArgsTool,
	"generate":            NewGenerateArgsTool,
	"marketplace_install": NewMarketplaceInstallArgsTool,
	"marketplace_list":    NewMarketplaceListArgsTool,
	"migrate_create":      NewMigrateCreateArgsTool,
	"migrate_down":        NewMigrateDownArgsTool,
	"migrate_reset":       NewMigrateResetArgsTool,
	"migrate_status":      NewMigrateStatusArgsTool,
	"migrate_up":          NewMigrateUpArgsTool,
	"migrate_validate":    NewMigrateValidateArgsTool,
	"migrate_version":     NewMigrateVersionArgsTool,
	"plan":                NewPlanArgsTool,
	"plan_req_add":        NewPlanReqAddArgsTool,
	"plan_req_list":       NewPlanReqListArgsTool,
	"queue_consume":       NewQueueConsumeArgsTool,
	"queue_publish":       NewQueuePublishArgsTool,
	"status":              NewStatusArgsTool,
	"upgrade":             NewUpgradeArgsTool,
}

// AddAdminArgs defines arguments for the add_admin command.
type AddAdminArgs struct {
}

// NewAddAdminArgsTool creates a RegisteredTool for add_admin.
func NewAddAdminArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "add_admin",
		Description: "Add a full Admin Dashboard module\nUsage: kthulu add admin",
		Handler: func(ctx context.Context, args AddAdminArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"add",
				"admin",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AddComponentArgs defines arguments for the add_component command.
type AddComponentArgs struct {
	Type          string `json:"type,omitempty" jsonschema:"description=Positional argument: type"`
	Name          string `json:"name,omitempty" jsonschema:"description=Positional argument: name"`
	Module        string `json:"module,omitempty" jsonschema:"description=Target module (auto-detected if empty)"`
	WithMigration bool   `json:"with-migration,omitempty" jsonschema:"description=Generate database migration"`
	WithTests     bool   `json:"with-tests,omitempty" jsonschema:"description=Generate tests"`
}

// NewAddComponentArgsTool creates a RegisteredTool for add_component.
func NewAddComponentArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "add_component",
		Description: "Add a new component to your project\nUsage: kthulu add component [type] [name] [flags]",
		Handler: func(ctx context.Context, args AddComponentArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"add",
				"component",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: type
			if args.Type != "" {
				resolved = append(resolved, args.Type)
			}
			// Positional: name
			if args.Name != "" {
				resolved = append(resolved, args.Name)
			}

			// Flags
			// Flag: --module
			if args.Module != "" {
				resolved = append(resolved, "--module", args.Module)
			}
			// Flag: --with-migration
			if args.WithMigration {
				resolved = append(resolved, "--with-migration")
			}
			// Flag: --with-tests
			if args.WithTests {
				resolved = append(resolved, "--with-tests")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AddModuleArgs defines arguments for the add_module command.
type AddModuleArgs struct {
	Name       string   `json:"name,omitempty" jsonschema:"description=Positional argument: name"`
	FieldType  []string `json:"field_type,omitempty" jsonschema:"description=Positional argument: field_type"`
	Admin      bool     `json:"admin,omitempty" jsonschema:"description=Generate Admin CRUD pages"`
	Compliance string   `json:"compliance,omitempty" jsonschema:"description=Compliance requirements (pci, sox, gdpr)"`
	Force      bool     `json:"force,omitempty" jsonschema:"description=Force add even if conflicts exist"`
	Prefix     string   `json:"prefix,omitempty" jsonschema:"description=Route prefix (e.g. /api/v1)"`
	Protected  bool     `json:"protected,omitempty" jsonschema:"description=Protect routes with authentication middleware"`
	With       []string `json:"with,omitempty" jsonschema:"description=Integration packages (stripe, oauth, etc)"`
	Yes        bool     `json:"yes,omitempty" jsonschema:"description=Skip confirmation prompts"`
}

// NewAddModuleArgsTool creates a RegisteredTool for add_module.
func NewAddModuleArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "add_module",
		Description: "Add a new module to your project with optional fields\nUsage: kthulu add module [name] [field:type...] [flags]",
		Handler: func(ctx context.Context, args AddModuleArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"add",
				"module",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: name
			if args.Name != "" {
				resolved = append(resolved, args.Name)
			}
			// Positional: field_type
			resolved = append(resolved, args.FieldType...)

			// Flags
			// Flag: --admin
			if args.Admin {
				resolved = append(resolved, "--admin")
			}
			// Flag: --compliance
			if args.Compliance != "" {
				resolved = append(resolved, "--compliance", args.Compliance)
			}
			// Flag: --force
			if args.Force {
				resolved = append(resolved, "--force")
			}
			// Flag: --prefix
			if args.Prefix != "" {
				resolved = append(resolved, "--prefix", args.Prefix)
			}
			// Flag: --protected
			if args.Protected {
				resolved = append(resolved, "--protected")
			}
			// Flag: --with
			for _, v := range args.With {
				resolved = append(resolved, "--with", v)
			}
			// Flag: --yes
			if args.Yes {
				resolved = append(resolved, "--yes")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AddRecipeArgs defines arguments for the add_recipe command.
type AddRecipeArgs struct {
	Name string `json:"name,omitempty" jsonschema:"description=Positional argument: name"`
}

// NewAddRecipeArgsTool creates a RegisteredTool for add_recipe.
func NewAddRecipeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "add_recipe",
		Description: "Add a complete recipe (stack of modules)\nUsage: kthulu add recipe [name]",
		Handler: func(ctx context.Context, args AddRecipeArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"add",
				"recipe",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: name
			if args.Name != "" {
				resolved = append(resolved, args.Name)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AiArgs defines arguments for the ai command.
type AiArgs struct {
	Prompt string `json:"prompt,omitempty" jsonschema:"description=Positional argument: prompt"`
}

// NewAiArgsTool creates a RegisteredTool for ai.
func NewAiArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "ai",
		Description: "🤖 AI-powered code generation and assistance\nUsage: kthulu ai [prompt]",
		Handler: func(ctx context.Context, args AiArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"ai",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: prompt
			if args.Prompt != "" {
				resolved = append(resolved, args.Prompt)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AiGenFeatureArgs defines arguments for the ai_gen-feature command.
type AiGenFeatureArgs struct {
	Description string `json:"description,omitempty" jsonschema:"description=Positional argument: description"`
}

// NewAiGenFeatureArgsTool creates a RegisteredTool for ai_gen-feature.
func NewAiGenFeatureArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "ai_gen-feature",
		Description: "Generate a BDD feature file\nUsage: kthulu ai gen-feature [description]",
		Handler: func(ctx context.Context, args AiGenFeatureArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"ai",
				"gen-feature",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: description
			if args.Description != "" {
				resolved = append(resolved, args.Description)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AiGenStepsArgs defines arguments for the ai_gen-steps command.
type AiGenStepsArgs struct {
	FeatureFile string `json:"feature_file,omitempty" jsonschema:"description=Positional argument: feature_file"`
}

// NewAiGenStepsArgsTool creates a RegisteredTool for ai_gen-steps.
func NewAiGenStepsArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "ai_gen-steps",
		Description: "Generate step definitions for a feature\nUsage: kthulu ai gen-steps [feature_file]",
		Handler: func(ctx context.Context, args AiGenStepsArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"ai",
				"gen-steps",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: feature_file
			if args.FeatureFile != "" {
				resolved = append(resolved, args.FeatureFile)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AiOptimizeArgs defines arguments for the ai_optimize command.
type AiOptimizeArgs struct {
	Benchmark bool   `json:"benchmark,omitempty" jsonschema:"description=Run benchmarks before and after optimization"`
	Target    string `json:"target,omitempty" jsonschema:"description=Optimization target (performance, memory, scalability)"`
}

// NewAiOptimizeArgsTool creates a RegisteredTool for ai_optimize.
func NewAiOptimizeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "ai_optimize",
		Description: "⚡ AI-powered performance optimization\nUsage: kthulu ai optimize [flags]",
		Handler: func(ctx context.Context, args AiOptimizeArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"ai",
				"optimize",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --benchmark
			if args.Benchmark {
				resolved = append(resolved, "--benchmark")
			}
			// Flag: --target
			if args.Target != "" {
				resolved = append(resolved, "--target", args.Target)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AiReviewArgs defines arguments for the ai_review command.
type AiReviewArgs struct {
	Compliance     string `json:"compliance,omitempty" jsonschema:"description=Check compliance (sox, gdpr, pci)"`
	FixAll         bool   `json:"fix-all,omitempty" jsonschema:"description=Fix all detected issues"`
	FixPerformance bool   `json:"fix-performance,omitempty" jsonschema:"description=Fix performance issues"`
	FixSecurity    bool   `json:"fix-security,omitempty" jsonschema:"description=Fix security vulnerabilities"`
}

// NewAiReviewArgsTool creates a RegisteredTool for ai_review.
func NewAiReviewArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "ai_review",
		Description: "📝 AI-powered code review and fixes\nUsage: kthulu ai review [flags]",
		Handler: func(ctx context.Context, args AiReviewArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"ai",
				"review",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --compliance
			if args.Compliance != "" {
				resolved = append(resolved, "--compliance", args.Compliance)
			}
			// Flag: --fix-all
			if args.FixAll {
				resolved = append(resolved, "--fix-all")
			}
			// Flag: --fix-performance
			if args.FixPerformance {
				resolved = append(resolved, "--fix-performance")
			}
			// Flag: --fix-security
			if args.FixSecurity {
				resolved = append(resolved, "--fix-security")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AiScaffoldArgs defines arguments for the ai_scaffold command.
type AiScaffoldArgs struct {
	Description string `json:"description,omitempty" jsonschema:"description=Positional argument: description"`
	Output      string `json:"output,omitempty" jsonschema:"description=Output file for the plan"`
}

// NewAiScaffoldArgsTool creates a RegisteredTool for ai_scaffold.
func NewAiScaffoldArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "ai_scaffold",
		Description: "🏗️  AI-powered project scaffolding\nUsage: kthulu ai scaffold [description] [flags]",
		Handler: func(ctx context.Context, args AiScaffoldArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"ai",
				"scaffold",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: description
			if args.Description != "" {
				resolved = append(resolved, args.Description)
			}

			// Flags
			// Flag: --output
			if args.Output != "" {
				resolved = append(resolved, "--output", args.Output)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AnalyzeArgs defines arguments for the analyze command.
type AnalyzeArgs struct {
	Dir      string `json:"dir,omitempty" jsonschema:"description=Positional argument: dir"`
	Format   string `json:"format,omitempty" jsonschema:"description=Graph format: dot, json or yaml"`
	Graph    bool   `json:"graph,omitempty" jsonschema:"description=Generate and export validation graph"`
	Validate bool   `json:"validate,omitempty" jsonschema:"description=Validate graph and report violations"`
}

// NewAnalyzeArgsTool creates a RegisteredTool for analyze.
func NewAnalyzeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "analyze",
		Description: "Analyze overrides and extends annotations in the project\nUsage: kthulu analyze [dir] [flags]",
		Handler: func(ctx context.Context, args AnalyzeArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"analyze",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: dir
			if args.Dir != "" {
				resolved = append(resolved, args.Dir)
			}

			// Flags
			// Flag: --format
			if args.Format != "" {
				resolved = append(resolved, "--format", args.Format)
			}
			// Flag: --graph
			if args.Graph {
				resolved = append(resolved, "--graph")
			}
			// Flag: --validate
			if args.Validate {
				resolved = append(resolved, "--validate")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// AuditArgs defines arguments for the audit command.
type AuditArgs struct {
	Compliance   string `json:"compliance,omitempty" jsonschema:"description=Compliance standard (sox, gdpr, pci)"`
	Dependencies bool   `json:"dependencies,omitempty" jsonschema:"description=Check dependency vulnerabilities"`
	Fix          bool   `json:"fix,omitempty" jsonschema:"description=Automatically fix found issues"`
	Security     bool   `json:"security,omitempty" jsonschema:"description=Run security analysis"`
}

// NewAuditArgsTool creates a RegisteredTool for audit.
func NewAuditArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "audit",
		Description: "🔍 Enterprise security and compliance auditing\nUsage: kthulu audit [flags]",
		Handler: func(ctx context.Context, args AuditArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"audit",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --compliance
			if args.Compliance != "" {
				resolved = append(resolved, "--compliance", args.Compliance)
			}
			// Flag: --dependencies
			if args.Dependencies {
				resolved = append(resolved, "--dependencies")
			}
			// Flag: --fix
			if args.Fix {
				resolved = append(resolved, "--fix")
			}
			// Flag: --security
			if args.Security {
				resolved = append(resolved, "--security")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// BddFeaturesArgs defines arguments for the bdd_features command.
type BddFeaturesArgs struct {
}

// NewBddFeaturesArgsTool creates a RegisteredTool for bdd_features.
func NewBddFeaturesArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "bdd_features",
		Description: "List all feature files\nUsage: kthulu bdd features",
		Handler: func(ctx context.Context, args BddFeaturesArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"bdd",
				"features",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// BddRunArgs defines arguments for the bdd_run command.
type BddRunArgs struct {
	Filter string `json:"filter,omitempty" jsonschema:"description=Filter scenarios to run"`
}

// NewBddRunArgsTool creates a RegisteredTool for bdd_run.
func NewBddRunArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "bdd_run",
		Description: "Run BDD scenarios\nUsage: kthulu bdd run [flags]",
		Handler: func(ctx context.Context, args BddRunArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"bdd",
				"run",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --filter
			if args.Filter != "" {
				resolved = append(resolved, "--filter", args.Filter)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// ClaudeArgs defines arguments for the claude command.
type ClaudeArgs struct {
}

// NewClaudeArgsTool creates a RegisteredTool for claude.
func NewClaudeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "claude",
		Description: "🤖 Configure and launch Claude CLI with Kthulu superpowers\nUsage: kthulu claude",
		Handler: func(ctx context.Context, args ClaudeArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"claude",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// CoderArgs defines arguments for the coder command.
type CoderArgs struct {
	Model string `json:"model,omitempty" jsonschema:"description=AI model to use (e.g., gemini-2.5-flash, claude-3-sonnet)"`
}

// NewCoderArgsTool creates a RegisteredTool for coder.
func NewCoderArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "coder",
		Description: "🐙 AI-powered coding assistant with a beautiful TUI\nUsage: kthulu coder [flags]",
		Handler: func(ctx context.Context, args CoderArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"coder",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --model
			if args.Model != "" {
				resolved = append(resolved, "--model", args.Model)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// CompileArgs defines arguments for the compile command.
type CompileArgs struct {
	Out   string `json:"out,omitempty" jsonschema:"description=Output directory"`
	Watch bool   `json:"watch,omitempty" jsonschema:"description=Watch for changes"`
}

// NewCompileArgsTool creates a RegisteredTool for compile.
func NewCompileArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "compile",
		Description: "Compile overrides and extensions\nUsage: kthulu compile [flags]",
		Handler: func(ctx context.Context, args CompileArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"compile",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --out
			if args.Out != "" {
				resolved = append(resolved, "--out", args.Out)
			}
			// Flag: --watch
			if args.Watch {
				resolved = append(resolved, "--watch")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// CreateArgs defines arguments for the create command.
type CreateArgs struct {
	Name          string   `json:"name,omitempty" jsonschema:"description=Positional argument: name"`
	Auth          string   `json:"auth,omitempty" jsonschema:"description=Auth type (jwt, oauth, both)"`
	Database      string   `json:"database,omitempty" jsonschema:"description=Database type (sqlite, postgres, mysql)"`
	DryRun        bool     `json:"dry-run,omitempty" jsonschema:"description=Show what would be generated without creating files"`
	Enterprise    bool     `json:"enterprise,omitempty" jsonschema:"description=Enable enterprise features"`
	Features      []string `json:"features,omitempty" jsonschema:"description=Comma-separated list of features/modules"`
	FromPlan      string   `json:"from-plan,omitempty" jsonschema:"description=Create project from plan file"`
	Frontend      string   `json:"frontend,omitempty" jsonschema:"description=Frontend type: templ (GTH - default), none"`
	Interactive   bool     `json:"interactive,omitempty" jsonschema:"description=Interactive project configuration"`
	ModulePath    string   `json:"module-path,omitempty" jsonschema:"description=Go module path (default: project name)"`
	NoVercel      bool     `json:"no-vercel,omitempty" jsonschema:"description=Skip Vercel deployment files"`
	Observability bool     `json:"observability,omitempty" jsonschema:"description=Enable observability stack"`
	Output        string   `json:"output,omitempty" jsonschema:"description=Output directory (default: current directory)"`
	Template      string   `json:"template,omitempty" jsonschema:"description=Project template"`
}

// NewCreateArgsTool creates a RegisteredTool for create.
func NewCreateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "create",
		Description: "🚀 Create a new Kthulu project (The easy way)\nUsage: kthulu create [name] [flags]",
		Handler: func(ctx context.Context, args CreateArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"create",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: name
			if args.Name != "" {
				resolved = append(resolved, args.Name)
			}

			// Flags
			// Flag: --auth
			if args.Auth != "" {
				resolved = append(resolved, "--auth", args.Auth)
			}
			// Flag: --database
			if args.Database != "" {
				resolved = append(resolved, "--database", args.Database)
			}
			// Flag: --dry-run
			if args.DryRun {
				resolved = append(resolved, "--dry-run")
			}
			// Flag: --enterprise
			if args.Enterprise {
				resolved = append(resolved, "--enterprise")
			}
			// Flag: --features
			for _, v := range args.Features {
				resolved = append(resolved, "--features", v)
			}
			// Flag: --from-plan
			if args.FromPlan != "" {
				resolved = append(resolved, "--from-plan", args.FromPlan)
			}
			// Flag: --frontend
			if args.Frontend != "" {
				resolved = append(resolved, "--frontend", args.Frontend)
			}
			// Flag: --interactive
			if args.Interactive {
				resolved = append(resolved, "--interactive")
			}
			// Flag: --module-path
			if args.ModulePath != "" {
				resolved = append(resolved, "--module-path", args.ModulePath)
			}
			// Flag: --no-vercel
			if args.NoVercel {
				resolved = append(resolved, "--no-vercel")
			}
			// Flag: --observability
			if args.Observability {
				resolved = append(resolved, "--observability")
			}
			// Flag: --output
			if args.Output != "" {
				resolved = append(resolved, "--output", args.Output)
			}
			// Flag: --template
			if args.Template != "" {
				resolved = append(resolved, "--template", args.Template)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// DebugArgs defines arguments for the debug command.
type DebugArgs struct {
	Cmd       string `json:"cmd,omitempty" jsonschema:"description=Command to run the application (default: auto-detect 'go run ...')"`
	Persist   bool   `json:"persist,omitempty" jsonschema:"description=Persist debug events to disk"`
	TestWatch bool   `json:"test-watch,omitempty" jsonschema:"description=Watch tests and display status"`
}

// NewDebugArgsTool creates a RegisteredTool for debug.
func NewDebugArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "debug",
		Description: "🐞 Interactive debug daemon and runtime monitor\nUsage: kthulu debug [flags]",
		Handler: func(ctx context.Context, args DebugArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"debug",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --cmd
			if args.Cmd != "" {
				resolved = append(resolved, "--cmd", args.Cmd)
			}
			// Flag: --persist
			if args.Persist {
				resolved = append(resolved, "--persist")
			}
			// Flag: --test-watch
			if args.TestWatch {
				resolved = append(resolved, "--test-watch")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// DeployArgs defines arguments for the deploy command.
type DeployArgs struct {
	Cloud     string `json:"cloud,omitempty" jsonschema:"description=Cloud provider (aws, gcp, azure)"`
	Namespace string `json:"namespace,omitempty" jsonschema:"description=Kubernetes namespace"`
	Region    string `json:"region,omitempty" jsonschema:"description=Deployment region"`
	Scale     string `json:"scale,omitempty" jsonschema:"description=Scaling strategy (auto, manual, fixed)"`
}

// NewDeployArgsTool creates a RegisteredTool for deploy.
func NewDeployArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "deploy",
		Description: "🚀 Zero-config multi-cloud deployment\nUsage: kthulu deploy [flags]",
		Handler: func(ctx context.Context, args DeployArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"deploy",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --cloud
			if args.Cloud != "" {
				resolved = append(resolved, "--cloud", args.Cloud)
			}
			// Flag: --namespace
			if args.Namespace != "" {
				resolved = append(resolved, "--namespace", args.Namespace)
			}
			// Flag: --region
			if args.Region != "" {
				resolved = append(resolved, "--region", args.Region)
			}
			// Flag: --scale
			if args.Scale != "" {
				resolved = append(resolved, "--scale", args.Scale)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// DevArgs defines arguments for the dev command.
type DevArgs struct {
}

// NewDevArgsTool creates a RegisteredTool for dev.
func NewDevArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "dev",
		Description: "Start the self-healing development server\nUsage: kthulu dev",
		Handler: func(ctx context.Context, args DevArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"dev",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// DocArgs defines arguments for the doc command.
type DocArgs struct {
	Diagrams    bool   `json:"diagrams,omitempty" jsonschema:"description=Generate Mermaid architecture diagrams"`
	Dir         string `json:"dir,omitempty" jsonschema:"description=Directory to search for main.go (default: project root)"`
	GeneralInfo string `json:"generalInfo,omitempty" jsonschema:"description=API general info file (default: cmd/server/main.go)"`
}

// NewDocArgsTool creates a RegisteredTool for doc.
func NewDocArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "doc",
		Description: "📚 Generate API documentation\nUsage: kthulu doc [flags]",
		Handler: func(ctx context.Context, args DocArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"doc",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --diagrams
			if args.Diagrams {
				resolved = append(resolved, "--diagrams")
			}
			// Flag: --dir
			if args.Dir != "" {
				resolved = append(resolved, "--dir", args.Dir)
			}
			// Flag: --generalInfo
			if args.GeneralInfo != "" {
				resolved = append(resolved, "--generalInfo", args.GeneralInfo)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// DoctorArgs defines arguments for the doctor command.
type DoctorArgs struct {
	Verbose bool `json:"verbose,omitempty" jsonschema:"description=Show detailed output for checks"`
}

// NewDoctorArgsTool creates a RegisteredTool for doctor.
func NewDoctorArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "doctor",
		Description: "🩺 Diagnose your development environment\nUsage: kthulu doctor [flags]",
		Handler: func(ctx context.Context, args DoctorArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"doctor",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --verbose
			if args.Verbose {
				resolved = append(resolved, "--verbose")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// GeminiArgs defines arguments for the gemini command.
type GeminiArgs struct {
}

// NewGeminiArgsTool creates a RegisteredTool for gemini.
func NewGeminiArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "gemini",
		Description: "✨ Launch Gemini CLI with Kthulu Superpowers (Context + MCP)\nUsage: kthulu gemini",
		Handler: func(ctx context.Context, args GeminiArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"gemini",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// GenerateArgs defines arguments for the generate command.
type GenerateArgs struct {
	Prompt string `json:"prompt,omitempty" jsonschema:"description=Natural language description of what to build"`
}

// NewGenerateArgsTool creates a RegisteredTool for generate.
func NewGenerateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "generate",
		Description: "✨ Generate code from natural language prompts\nUsage: kthulu generate [flags]\nExamples:\nkthulu generate --prompt \"I need a blog module\"\n  kthulu generate --prompt \"create a user handler\"\n  kthulu generate --prompt \"add an admin dashboard\"",
		Handler: func(ctx context.Context, args GenerateArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"generate",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --prompt
			if args.Prompt != "" {
				resolved = append(resolved, "--prompt", args.Prompt)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MarketplaceInstallArgs defines arguments for the marketplace_install command.
type MarketplaceInstallArgs struct {
	Id   string `json:"id,omitempty" jsonschema:"description=Positional argument: id"`
	Repo string `json:"repo,omitempty" jsonschema:"description=Path to marketplace repository"`
}

// NewMarketplaceInstallArgsTool creates a RegisteredTool for marketplace_install.
func NewMarketplaceInstallArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "marketplace_install",
		Description: "Install a plugin or add a module\nUsage: kthulu marketplace install [id] [flags]",
		Handler: func(ctx context.Context, args MarketplaceInstallArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"marketplace",
				"install",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: id
			if args.Id != "" {
				resolved = append(resolved, args.Id)
			}

			// Flags
			// Flag: --repo
			if args.Repo != "" {
				resolved = append(resolved, "--repo", args.Repo)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MarketplaceListArgs defines arguments for the marketplace_list command.
type MarketplaceListArgs struct {
	Repo string `json:"repo,omitempty" jsonschema:"description=Path to marketplace repository"`
	Type string `json:"type,omitempty" jsonschema:"description=Filter by type (starter, module, plugin)"`
}

// NewMarketplaceListArgsTool creates a RegisteredTool for marketplace_list.
func NewMarketplaceListArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "marketplace_list",
		Description: "List available items\nUsage: kthulu marketplace list [flags]",
		Handler: func(ctx context.Context, args MarketplaceListArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"marketplace",
				"list",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --repo
			if args.Repo != "" {
				resolved = append(resolved, "--repo", args.Repo)
			}
			// Flag: --type
			if args.Type != "" {
				resolved = append(resolved, "--type", args.Type)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateCreateArgs defines arguments for the migrate_create command.
type MigrateCreateArgs struct {
	Name string `json:"name,omitempty" jsonschema:"description=Positional argument: name"`
}

// NewMigrateCreateArgsTool creates a RegisteredTool for migrate_create.
func NewMigrateCreateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_create",
		Description: "Create a new migration file\nUsage: kthulu migrate create [name]",
		Handler: func(ctx context.Context, args MigrateCreateArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"create",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: name
			if args.Name != "" {
				resolved = append(resolved, args.Name)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateDownArgs defines arguments for the migrate_down command.
type MigrateDownArgs struct {
}

// NewMigrateDownArgsTool creates a RegisteredTool for migrate_down.
func NewMigrateDownArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_down",
		Description: "Revert the last migration\nUsage: kthulu migrate down",
		Handler: func(ctx context.Context, args MigrateDownArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"down",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateResetArgs defines arguments for the migrate_reset command.
type MigrateResetArgs struct {
}

// NewMigrateResetArgsTool creates a RegisteredTool for migrate_reset.
func NewMigrateResetArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_reset",
		Description: "Reset database and reapply all migrations\nUsage: kthulu migrate reset",
		Handler: func(ctx context.Context, args MigrateResetArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"reset",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateStatusArgs defines arguments for the migrate_status command.
type MigrateStatusArgs struct {
}

// NewMigrateStatusArgsTool creates a RegisteredTool for migrate_status.
func NewMigrateStatusArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_status",
		Description: "Show current database version\nUsage: kthulu migrate status",
		Handler: func(ctx context.Context, args MigrateStatusArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"status",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateUpArgs defines arguments for the migrate_up command.
type MigrateUpArgs struct {
}

// NewMigrateUpArgsTool creates a RegisteredTool for migrate_up.
func NewMigrateUpArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_up",
		Description: "Apply all pending migrations\nUsage: kthulu migrate up",
		Handler: func(ctx context.Context, args MigrateUpArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"up",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateValidateArgs defines arguments for the migrate_validate command.
type MigrateValidateArgs struct {
}

// NewMigrateValidateArgsTool creates a RegisteredTool for migrate_validate.
func NewMigrateValidateArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_validate",
		Description: "Validate all migrations are correct\nUsage: kthulu migrate validate",
		Handler: func(ctx context.Context, args MigrateValidateArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"validate",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// MigrateVersionArgs defines arguments for the migrate_version command.
type MigrateVersionArgs struct {
	Target string `json:"target,omitempty" jsonschema:"description=Positional argument: target"`
}

// NewMigrateVersionArgsTool creates a RegisteredTool for migrate_version.
func NewMigrateVersionArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "migrate_version",
		Description: "Migrate database to a specific version\nUsage: kthulu migrate version [target]",
		Handler: func(ctx context.Context, args MigrateVersionArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"migrate",
				"version",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: target
			if args.Target != "" {
				resolved = append(resolved, args.Target)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// PlanArgs defines arguments for the plan command.
type PlanArgs struct {
	Name     string   `json:"name,omitempty" jsonschema:"description=Positional argument: name"`
	Features []string `json:"features,omitempty" jsonschema:"description=Features/modules"`
	Output   string   `json:"output,omitempty" jsonschema:"description=Output file for the plan"`
	Template string   `json:"template,omitempty" jsonschema:"description=Project template"`
}

// NewPlanArgsTool creates a RegisteredTool for plan.
func NewPlanArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "plan",
		Description: "📋 Plan a new project configuration\nUsage: kthulu plan [name] [flags]",
		Handler: func(ctx context.Context, args PlanArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"plan",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: name
			if args.Name != "" {
				resolved = append(resolved, args.Name)
			}

			// Flags
			// Flag: --features
			for _, v := range args.Features {
				resolved = append(resolved, "--features", v)
			}
			// Flag: --output
			if args.Output != "" {
				resolved = append(resolved, "--output", args.Output)
			}
			// Flag: --template
			if args.Template != "" {
				resolved = append(resolved, "--template", args.Template)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// PlanReqAddArgs defines arguments for the plan_req_add command.
type PlanReqAddArgs struct {
	Title    string `json:"title,omitempty" jsonschema:"description=Positional argument: title"`
	Desc     string `json:"desc,omitempty" jsonschema:"description=Description of the requirement"`
	Priority string `json:"priority,omitempty" jsonschema:"description=Priority (High, Medium, Low)"`
}

// NewPlanReqAddArgsTool creates a RegisteredTool for plan_req_add.
func NewPlanReqAddArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "plan_req_add",
		Description: "Add a new requirement\nUsage: kthulu plan req add [title] [flags]",
		Handler: func(ctx context.Context, args PlanReqAddArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"plan",
				"req",
				"add",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: title
			if args.Title != "" {
				resolved = append(resolved, args.Title)
			}

			// Flags
			// Flag: --desc
			if args.Desc != "" {
				resolved = append(resolved, "--desc", args.Desc)
			}
			// Flag: --priority
			if args.Priority != "" {
				resolved = append(resolved, "--priority", args.Priority)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// PlanReqListArgs defines arguments for the plan_req_list command.
type PlanReqListArgs struct {
}

// NewPlanReqListArgsTool creates a RegisteredTool for plan_req_list.
func NewPlanReqListArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "plan_req_list",
		Description: "List all requirements\nUsage: kthulu plan req list",
		Handler: func(ctx context.Context, args PlanReqListArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"plan",
				"req",
				"list",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// QueueConsumeArgs defines arguments for the queue_consume command.
type QueueConsumeArgs struct {
	Queue string `json:"queue,omitempty" jsonschema:"description=Positional argument: queue"`
}

// NewQueueConsumeArgsTool creates a RegisteredTool for queue_consume.
func NewQueueConsumeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "queue_consume",
		Description: "Consume messages from a queue\nUsage: kthulu queue consume [queue]",
		Handler: func(ctx context.Context, args QueueConsumeArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"queue",
				"consume",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: queue
			if args.Queue != "" {
				resolved = append(resolved, args.Queue)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// QueuePublishArgs defines arguments for the queue_publish command.
type QueuePublishArgs struct {
	Queue   string `json:"queue,omitempty" jsonschema:"description=Positional argument: queue"`
	Message string `json:"message,omitempty" jsonschema:"description=Positional argument: message"`
}

// NewQueuePublishArgsTool creates a RegisteredTool for queue_publish.
func NewQueuePublishArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "queue_publish",
		Description: "Publish a message to a queue\nUsage: kthulu queue publish [queue] [message]",
		Handler: func(ctx context.Context, args QueuePublishArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"queue",
				"publish",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)
			// Positional: queue
			if args.Queue != "" {
				resolved = append(resolved, args.Queue)
			}
			// Positional: message
			if args.Message != "" {
				resolved = append(resolved, args.Message)
			}

			// Flags

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// StatusArgs defines arguments for the status command.
type StatusArgs struct {
	Detailed bool `json:"detailed,omitempty" jsonschema:"description=Show detailed information"`
	Modules  bool `json:"modules,omitempty" jsonschema:"description=Focus on module information"`
}

// NewStatusArgsTool creates a RegisteredTool for status.
func NewStatusArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "status",
		Description: "📊 Project health and status overview\nUsage: kthulu status [flags]",
		Handler: func(ctx context.Context, args StatusArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"status",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --detailed
			if args.Detailed {
				resolved = append(resolved, "--detailed")
			}
			// Flag: --modules
			if args.Modules {
				resolved = append(resolved, "--modules")
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}

// UpgradeArgs defines arguments for the upgrade command.
type UpgradeArgs struct {
	DryRun  bool   `json:"dry-run,omitempty" jsonschema:"description=Preview changes without applying"`
	Version string `json:"version,omitempty" jsonschema:"description=Target version"`
}

// NewUpgradeArgsTool creates a RegisteredTool for upgrade.
func NewUpgradeArgsTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name:        "upgrade",
		Description: "📈 Upgrade framework and dependencies\nUsage: kthulu upgrade [flags]",
		Handler: func(ctx context.Context, args UpgradeArgs) (*mcp_golang.ToolResponse, error) {
			baseArgs := []string{
				"upgrade",
			}

			// Resolve arguments
			var resolved []string
			resolved = append(resolved, baseArgs...)

			// Flags
			// Flag: --dry-run
			if args.DryRun {
				resolved = append(resolved, "--dry-run")
			}
			// Flag: --version
			if args.Version != "" {
				resolved = append(resolved, "--version", args.Version)
			}

			// Execute
			result, err := executor.Run(ctx, workingDir, resolved)
			commandLabel := strings.Join(append([]string{"kthulu"}, resolved...), " ")
			response := formatCommandResult(commandLabel, workingDir, result)

			if err != nil {
				return nil, fmt.Errorf("%s failed: %w\nSTDOUT:\n%s\nSTDERR:\n%s", commandLabel, err, normalizeOutput(result.Stdout), normalizeOutput(result.Stderr))
			}

			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(response)), nil
		},
	}
}
