package mcp

import (
	"bytes"
	"fmt"
	"go/format"
	"strings"
	"text/template"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// ArgDef describes a positional argument derived from the Cobra command.
type ArgDef struct {
	Name        string
	Description string
	Variadic    bool
	Optional    bool
	Index       int
	PascalName  string
}

// FlagDef describes a flag derived from the Cobra command.
type FlagDef struct {
	Name        string
	Description string
	Type        string
	PascalName  string
}

// ToolDef describes a tool to be generated.
type ToolDef struct {
	Name        string
	Description string
	StructName  string
	Args        []ArgDef
	Flags       []FlagDef
	BaseArgs    []string // e.g. ["add", "module"]
}

// GenerateToolsCode analyzes the Cobra command tree and generates Go code for MCP tools.
func GenerateToolsCode(root *cobra.Command) (string, error) {
	tools := collectTools(root)

	tmpl := template.Must(template.New("tools").Parse(toolsTemplate))
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, tools); err != nil {
		return "", err
	}

	// Format the code
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.String(), fmt.Errorf("formatting failed: %w", err)
	}

	return string(formatted), nil
}

func collectTools(root *cobra.Command) []ToolDef {
	var tools []ToolDef
	for _, cmd := range collectRunnableCommands(root) {
		segments := commandSegments(cmd)
		if len(segments) == 0 {
			continue
		}

		name := strings.Join(segments, "_")
		structName := toPascalCase(name) + "Args"

		argDefs := parseCommandArgs(cmd)
		flagDefs := parseCommandFlags(cmd)

		tool := ToolDef{
			Name:        name,
			Description: buildDescription(cmd),
			StructName:  structName,
			Args:        argDefs,
			Flags:       flagDefs,
			BaseArgs:    segments,
		}
		tools = append(tools, tool)
	}
	return tools
}

func parseCommandArgs(cmd *cobra.Command) []ArgDef {
	use := cmd.Use
	parts := strings.Fields(use)
	if len(parts) < 2 {
		return nil
	}

	var args []ArgDef
	// Skip the first part (command name)
	for i, part := range parts[1:] {
		arg := ArgDef{Index: i}
		clean := part

		if strings.HasPrefix(clean, "[") && strings.HasSuffix(clean, "]") {
			arg.Optional = true
			clean = strings.TrimPrefix(clean, "[")
			clean = strings.TrimSuffix(clean, "]")
		} else if strings.HasPrefix(clean, "<") && strings.HasSuffix(clean, ">") {
			arg.Optional = false
			clean = strings.TrimPrefix(clean, "<")
			clean = strings.TrimSuffix(clean, ">")
		}

		if strings.HasSuffix(clean, "...") {
			arg.Variadic = true
			clean = strings.TrimSuffix(clean, "...")
		}

		clean = strings.ReplaceAll(clean, "|", "_or_")
		clean = strings.ReplaceAll(clean, ":", "_")

		arg.Name = clean
		arg.Description = fmt.Sprintf("Positional argument: %s", clean)
		arg.PascalName = toPascalCase(clean)

		args = append(args, arg)
	}
	return args
}

func parseCommandFlags(cmd *cobra.Command) []FlagDef {
	var flags []FlagDef
	cmd.Flags().VisitAll(func(f *pflag.Flag) {
		flags = append(flags, FlagDef{
			Name:        f.Name,
			Description: f.Usage,
			Type:        f.Value.Type(),
			PascalName:  toPascalCase(f.Name),
		})
	})
	return flags
}

func toPascalCase(s string) string {
	s = strings.ReplaceAll(s, ":", "_")
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, ".", "")

	parts := strings.Split(s, "_")
	var res string
	for _, p := range parts {
		if len(p) > 0 {
			res += strings.ToUpper(p[:1]) + p[1:]
		}
	}
	if len(res) == 0 {
		return "Field"
	}
	return res
}

const toolsTemplate = `// Code generated by kthulu mcp-schema-gen. DO NOT EDIT.
package mcp

// GeneratedToolRegistry maps tool names to their factory functions.
var GeneratedToolRegistry = map[string]func(Executor CommandExecutor, workingDir string) RegisteredTool{
{{- range . }}
	"{{ .Name }}": New{{ .StructName }}Tool,
{{- end }}
}

{{- range . }}

// {{ .StructName }} defines arguments for the {{ .Name }} command.
type {{ .StructName }} struct {
{{- range .Args }}
	{{ .PascalName }} {{ if .Variadic }}[]string{{ else }}string{{ end }} ` + "`" + `json:"{{ .Name }}{{ if .Optional }},omitempty{{ end }}" jsonschema:"description={{ .Description }}" kthulu:"pos,index={{ .Index }}{{ if .Variadic }},variadic{{ end }}"` + "`" + `
{{- end }}
{{- range .Flags }}
	{{ .PascalName }} {{ if eq .Type "bool" }}bool{{ else if eq .Type "stringSlice" }}[]string{{ else if eq .Type "int" }}int{{ else }}string{{ end }} ` + "`" + `json:"{{ .Name }},omitempty" jsonschema:"description={{ .Description }}" kthulu:"flag,name={{ .Name }}"` + "`" + `
{{- end }}
}

// New{{ .StructName }}Tool creates a RegisteredTool for {{ .Name }}.
func New{{ .StructName }}Tool(executor CommandExecutor, workingDir string) RegisteredTool {
	return NewReflectTool[{{ .StructName }}](
		"{{ .Name }}",
		{{ printf "%q" .Description }},
		[]string{
			{{- range .BaseArgs }}
			"{{ . }}",
			{{- end }}
		},
		executor,
		workingDir,
	)
}
{{- end }}
`
