package mcp

import (
	"context"
	"fmt"
	"strings"

	mcp_golang "github.com/metoro-io/mcp-golang"
)

// MigratePreviewArgs for migrate_preview.
type MigratePreviewArgs struct {
	Save bool `json:"save,omitempty" jsonschema:"description=If true, save the migration file to disk (same as migrate diff). Default false shows SQL without writing."`
}

func migratePreviewTool(executor CommandExecutor, workingDir string) RegisteredTool {
	return RegisteredTool{
		Name: "migrate_preview",
		Description: "Show the SQL that would be generated by the next migration (kthulu migrate diff) WITHOUT writing the file. " +
			"Use this before add_field or any schema change to verify the SQL is correct. " +
			"Set save=true to also write the migration file to disk.",
		Handler: func(ctx context.Context, args MigratePreviewArgs) (*mcp_golang.ToolResponse, error) {
			dir := resolveWorkdir(workingDir)

			cmdArgs := []string{"migrate", "diff"}
			if !args.Save {
				cmdArgs = append(cmdArgs, "--dry-run")
			}

			result, err := executor.Run(ctx, dir, cmdArgs)
			out := strings.TrimSpace(result.Stdout)
			if strings.TrimSpace(result.Stderr) != "" {
				out += "\n" + strings.TrimSpace(result.Stderr)
			}

			if err != nil {
				if strings.Contains(out, "no changes") || strings.Contains(out, "up to date") {
					return mcp_golang.NewToolResponse(mcp_golang.NewTextContent("✅ Schema is up to date — no migration needed.")), nil
				}
				return nil, fmt.Errorf("migrate diff failed: %w\n%s", err, out)
			}

			prefix := "🔍 Migration preview (not saved):"
			if args.Save {
				prefix = "✅ Migration file written:"
			}
			return mcp_golang.NewToolResponse(mcp_golang.NewTextContent(prefix + "\n\n" + out)), nil
		},
	}
}

func init() {
	RegisterPlugin(func(executor CommandExecutor, workingDir string) []RegisteredTool {
		return []RegisteredTool{migratePreviewTool(executor, workingDir)}
	})
}
